# Введение в SQL

## Введение в базы данных

### Введение в базы данных

**Базы данных и системы управления базами данных**

Данные -- зарегистрированная информация; представление фактов, понятий или инструкций в форме, приемлемой для общения, интерпретации, или обработки человеком или с помощью автоматических средств [[источник]](https://ru.wikipedia.org/wiki/%D0%94%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5).

Данные -- это отдельные упорядоченные факты, характеризующие объекты,
процессы и явления предметной области, а также их свойства [[1]](#TA_Gavrilova).

База данных -- это некоторый набор постоянно хранимых данных, используемых прикладными программными системами какого-либо предприятия [[2]](#CJ_Date).

База данных -- организованная в соответствии с определенными правилами и поддерживаемая в памяти компьютера совокупность данных, характеризующая актуальное состояние некоторой предметной области и используемая для удовлетворения информационных потребностей пользователей [[3]](#MR_Kogalowski).

Совокупность данных, хранимых под управлением СУБД, называется базой данных [[4]](#BA_Novikov).

Система управления базами данных (СУБД) -- это программный комплекс, обеспечивающий централизованное хранение данных и предоставляющий приложениям услуги по обработке данных [[4]](#BA_Novikov).

Таким образом, **данные** аккумулируются и составляют **базы данных**, с которыми, в свою очередь, работают (создают, наполняют, модифицируют и осуществляют поиск) **системы управления базами данных**.

Требования к СУБД:

|Требование|Комментарий|
|--:|:--|
|Разделение программ и данных|Описание структуры данных должно быть отделено от кода приложения|
|Высокоуровневый язык запросов|Система должна предоставлять средства для обработки данных, не включенные в какое-либо приложение|
|Целостность|Система должна предотвращать запись данных, нарушающих заранее специфицированные ограничения|
|Согласованность|Система должна предотвращать появление некорректностей в данных вследствие параллельной работы нескокльих приложений|
|Отказоустойчивость|СУБД не должна допускать потери данных даже в случае отказов оборудования|
|Защита и разграничение доступа|Система должна предоставлять каждому пользователю доступ только к части данных в соответствии с правами этого пользователя|

Наиболее распространенные СУБД [[источник]](https://public.flourish.studio/visualisation/6054072/?utm_source=showcase&utm_campaign=visualisation/6054072): `Oracle`, `MySQL`, `Microsoft SQL Server`, `PostgreSQL`, `MongoDB`, `IBM Db2`, `Redis`, `Elasticsearch`, `SQLite`, `Microsoft Access`.

СУБД классифицируются по разным признакам: способы доступа к БД; схема лицензирования.

Пример классификации СУБД по способу доступа к БД

|Класс СУБД|СУБД|Комментарий|
|--:|:--|:--|
|Клиент-серверные СУБД|Microsoft SQL Server, Oracle, Firebird, PostgreSQL, InterBase, MySQL|Вся обработка данных ведется в одном месте, на сервере, в том же месте, где хранятся данные|
|Файл-серверные СУБД|Paradox, Microsoft Access, FoxPro, dBase|Приложения имеют общий доступ ко всем файлам базы данных и совместно обрабатывают эти данные|
|Встраиваемые СУБД|SQLite, Firebird Embedded, Microsoft SQL Server Compact|Предназначены для локального хранения данных приложения и не рассчитаны на коллективное использование в сети|

**Архитектура <<клиент/ сервер>>** [[5]](#Manual_Microsoft).

Клиент/серверная архитектура описывает распределенные системы, состоящие из отдельных клиента и сервера и соединяющей их сети. Простейшая форма системы клиент/сервер, называемая 2-уровневой архитектурой -- это серверное приложение, к которому напрямую обращаются множество клиентов. Программы-серверы ожидают от клиентских программ запросы и предоставляют им свои ресурсы в виде данных. Общая схема клиент/серверной архитектуры представлена на [рисунке](https://habr.com/ru/post/495698/).

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=14MI3714_mJYrHBqvoQF94myUyYPfyeDw' width="500" height="300" />
<figcaption>Клиент/серверная архитектура</figcaption></center>
</figure>


Основные преимущества архитектурного стиля клиент/сервер:
- Большая безопасность. Все данные хранятся на сервере, который обычно
обеспечивает больший контроль безопасности, чем клиентские компьютеры.
- Централизованный доступ к данным. Поскольку данные хранятся только на сервере,
администрирование доступа к данным намного проще, чем в любых других
архитектурных стилях.
- Простота обслуживания. Роли и ответственность вычислительной системы
распределены между несколькими серверами, общающимися друг с другом по сети.
Благодаря этому клиент гарантированно остается неосведомленным и не
подверженным влиянию событий, происходящих с сервером (ремонт, обновление
либо перемещение).

Основной недостаток архитектурного стиля клиент/сервер состоит в связывании данных и бизнес-логики приложения на сервере.

**Моделирование и модели данных**

Моделирование данных -- начальный этап в проектировании базы данных, относится к процессу создания конкретной модели данных для определенной области.

Модель данных -- система взаимосвязанных понятий и правил, предназначенная для описания структур и свойств данных, используемых в информационной системе.

Состав модели данных:
- способы описания данных (какие базовые типы можно использовать, как строить сложные структуры данных из более простых);
- способы описания взаимодействия между объектами данных;
- средства задания ограничений целостности;
- способы конструирования операций, которые можно использовать в рамках модели данных.

При проектировании баз данных широко используется модель [<<сущность -- связь>>](https://ru.wikipedia.org/wiki/ER-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C).

Основными элементами модели данных являются *сущности*, *атрибуты*, *связи
(отношения)* и *ограничения*.

Сущность -- это объекты, о которых будут собираться и храниться данные.

Атрибут -- является свойством объекта.

Связь -- описывает отношение между сущностями. Модели данных используют три типа связи: один-ко-многим, многие-ко-многим и один-к-одному.

Ограничение -- это лимиты на данные. Ограничения важны, потому что они помогают
обеспечить целостность данных. Ограничения обычно выражаются в виде правил.

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=14Mi4J9ouWhbp_K4tzo-dHXYFAaVfZiC8' width="500" height="300" />
<figcaption>Пример ER-диаграммы</figcaption></center>
</figure>

Более подробно про нотацию ER-диаграмм можно почитать [здесь](https://www.lucidchart.com/pages/ru/erd-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0).


К настоящему моменту времени разработано достаточно много моделей данных.

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=14QVSIdWpIRN00ZBB9UDeAwFzBHvD6c-B' width="500" height="600" />
<figcaption>Эволюция моделей данных</figcaption></center>
</figure>

Наиболее распространенной считается [реляционная модель данных](https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85).


[Основные понятия](https://bstudy.net/732012/informatika/osnovnye_ponyatiya_relyatsionnyh_dannyh) реляционной модели данных: отношение, домен, атрибут, кортеж и первичный ключ.

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=14Te-BWcBoKK6eQoQwV03YjusviwPgA0C' width="500" height="300" />
<figcaption>Пример отношения</figcaption></center>
</figure>

Реляционная модель предусматривает способ представления данных в виде набора двумерных таблиц, которые называют отношениями.

Формально *отношение* определяется как $n$-местный предикат, т.е. функция с $n$ аргументами, принимающая булево значение: `true` или `false`.

Для каждого задан `домен` (тип), из которого могут выбираться значения этого атрибута.

Домен отношения (поле) -- множество атомарных значений одного и того же типа.

Аргументы отношения называются атрибутами отношения. Имена атрибутов одного отношения обязательно должны быть различны. С каждым атрибутом связан некоторый домен, из которого выбираются значения атрибута. Множество всех атрибутов называется схемой отношения.

Совокупность из $n$ значений, по одному значению для каждого атрибута, называется кортежем. Иными словами, кортеж -- это набор значений аргументов, для которого можно вычислить предикат, соответствующий отношению. Кортеж принадлежит отношению, если придикат принимает истинное значение на этом кортеже.

Пример. Сотрудники(ФИО := "Орлов В.В.", Год рождения := 1976, Должность := "Лаборант", Отдел = 1)

Каждый кортеж состоит из $n$ значений, поэтому отношения принято записывать в виде таблиц, содержащих $n$ колонок, соответствующий атрибутам отношения. а каждая строка таблицы соответствует одному кортежу. Порядок не важен.

<u>Замечание</u>. *Отношение* принято называть таблицей, атрибуты -- колонками или столбцами, а кортежи -- строками.

Множество атрибутов, от которого функционально зависят все атрибуты отношения, называется возможным ключом отношения. Возможный ключ называется минимальным, если после исключения из него любого атрибута оставшееся множество атрибутов не является возможным ключом. Один из минимальных ключей выбирается в качестве первичного ключа отношения. Значения первичного ключа, как и любого возможного ключа, уникальны и могут использоваться для идентификации записей.


**Нормализация**

Нормализация -- это процесс удаления избыточных данных.

Нормализация нужна для:
- Устранения аномалий;
- Повышения производительности;
- Повышения удобства управления данными.

Процесс нормализации --- это последовательный процесс приведения базы данных к эталонному виду, т.е. переход от одной нормальной формы к следующей.

Выделяют следующие нормальные формы:
- Первая нормальная форма (1NF);
- Вторая нормальная форма (2NF);
- Третья нормальная форма (3NF);
- Нормальная форма Бойса-Кодда (BCNF);
- Четвертая нормальная форма (4NF);
- Пятая нормальная форма (5NF);
- Доменно-ключевая нормальная форма (DKNF);
- Шестая нормальная форма (6NF).

База данных считается нормализованной, если она находится как минимум в третьей нормальной форме (3NF).

Для того, чтобы база данных находилась в 1 нормальной форме, необходимо чтобы ее таблицы соблюдали следующие реляционные принципы:
- В таблице не должно быть дублирующих строк;
- В каждой ячейке таблицы хранится атомарное значение (одно не составное значение);
- В столбце хранятся данные одного типа;
- Отсутствуют массивы и списки в любом виде.

Для того, чтобы база данных находилась во второй нормальной форме (2NF), необходимо чтобы ее таблицы удовлетворяли следующим требованиям:
- Таблица должна находиться в первой нормальной форме;
- Таблица должна иметь ключ;
- Все неключевые столбцы таблицы должны зависеть от полного ключа (в случае если он составной).

Главное правило второй нормальной формы (2NF) --- таблица должна иметь первичный ключ, по которому можно идентифицировать каждую строку.

Требование третьей нормальной формы (3NF) заключается в том, чтобы в таблицах отсутствовала транзитивная зависимость.

Транзитивная зависимость -- это когда неключевые столбцы зависят от значений других неключевых столбцов.


Требования нормальной формы Бойса-Кодда следующие:

- Таблица должна находиться в третьей нормальной форме;
- Ключевые атрибуты составного ключа не должны зависеть от неключевых атрибутов.

Главное правило нормальной формы Бойса-Кодда (BCNF) звучит следующим образом:

Часть составного первичного ключа не должна зависеть от неключевого столбца.

Первичный ключ -- особенное поле в SQL-таблице, которое позволяет однозначно идентифицировать каждую запись в ней. Первичный ключ имеет несколько свойств:
- каждая запись в таком поле должна быть уникальной;
- запись в поле не должна быть пустой;
- в одной таблице может быть только один ключ (существуют также составные ключи, которые могут включать в себя несколько полей, однако в этой статье мы не будем их рассматривать).

Внешний ключ нужен для того, чтобы связать две разные SQL-таблицы между собой. Внешний ключ таблицы должен соответствует значению первичного ключа таблицы, с которой он связан. Это помогает сохранять согласованность базы данных путем обеспечения так называемой «ссылочной целостности».


<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=160L6VoP2kz8mJfpFuLWF6_SdoVcvkT-J' width="400" height="400" />
<figcaption>Структура базы </figcaption></center>
</figure>


## Литература
1. <a name="TA_Gavrilova"></a> Гаврилова Т.А., Кудрявцев Д.В., Муромцев Д.И. Инженерия знаний. Модели и методы. -- СПб.: Лань, 2016. -- 324 с.
2. <a name="CJ_Date"></a> Дейт К.Дж. Введение в системы баз данных. --  8-е издание. -- М.: Вильямс, 2005. -- 1328 с.
3. <a name="MR_Kogalowski"></a> Когаловский М.Р. Энциклопедия технологий баз данных. -- ­ М.: Финансы и статистика, 2005. -- 800 с.
4. <a name="BA_Novikov"></a> Новиков Б.А. Основы технологий баз данных. -- 2-е изд. -- М.: ДМК Пресс, 2020. -- 582 с.
5. <a name="Manual_Microsoft"></a> Руководство Microsoft по проектированию архитектуры приложений. -- 2-е изд. -- 2009. -- 529 с.

Облачные сервисы для работы с СУБД

1. MySQL -- https://sprinthost.ru/
2. PostgreSQL -- https://console.neon.tech/sign_in?ref=/

### Введение в SQL

**Язык SQL**

SQL (от англ. Structured Query Language -- язык структурированных запросов) --  декларативный язык программирования, применяемый для создания, модификации и управления данными в реляционной базе данных, управляемой соответствующей системой управления базами данных [[источник]](https://ru.wikipedia.org/wiki/SQL).
Язык SQL представляет собой совокупность инструкций, операторов, вычисляемых функций.

**sql-запрос**

Взаимодействие пользователя с СУБД осуществляется посредством так называемых sql-запросов или инструкций.

```sql
SELECT *
 FROM book
```

<u>Замечание</u> Понятия <<инструкция>> и <<sql-запрос>> на практике часто употребляются как синонимы.

SQL-запрос -- это набор команд для работы с реляционными базами данных.

Инструкция SQL состоит из нескольких частей, называемых предложениями. Каждое предложение в инструкции SQL имеет свое назначение. Некоторые предложения являются обязательными. Каждая инструкция должна завершаться `;`.

Компонентами инструкции могут быть ключевое слово, идентификатор,  строка (или константа) или специальный символ. Компоненты обычно разделяются пробельными символами (пробел, табуляция, перевод строки), но это не требуется.

<u>Замечание</u>. При написании запросов рекомендуется придерживаться [Руководства по стилю SQL](https://www.sqlstyle.guide/ru/).

**Ключевые слова и идентификаторы**

Ключевые слова -- слова, имеющие фиксированное значение в языке SQL (например, операторы или функции). Ключевые слова могут быть зарезервированными и незарезервированными. [Здесь](https://postgrespro.ru/docs/postgrespro/9.6/sql-keywords-appendix) можно посмотреть список.

Согласно стандарту, действительно ключевыми словами являются только зарезервированные слова.

В соответствии со стандартом, **зарезервированные ключевые слова нельзя** использовать для именования объектов базы данных, таких как таблицы, столбцы и пользователи.

Незарезервированные ключевые слова имеют особое значение только в определенных контекстах и могут быть идентификаторами в других. Большинство незарезервированных ключевых слов на самом деле представляют имена встроенных таблиц и функций, определенных в SQL.

Идентификаторы задаются пользователем и применяются для определения имен таблиц, столбцов или других объектов баз данных.

Идентификаторы и ключевые слова в SQL должны начинаться с буквы (a-z, хотя допускаются также не латинские буквы и буквы с диакритическими знаками) или нижнего подчеркивания (_). Последующими символами в идентификаторе или ключевом слове могут быть буквы, цифры (0-9), знак нижнего подчеркивания.

**Типы данных**

Типы данных SQL разделяются на три группы:
- строковые;
- с плавающей точкой (дробные числа);
- целые числа, дата и время.

Подробнее можно посмотреть [здесь](https://sql-language.ru/osnova-sql/tipy-dannykh-sql.html).

К основным принято относить следующие:

|Тип данных|Описание|
|--:|:--|
|`VARCHAR(size)`|Может хранить не более 255 символов|
|`FLOAT(size,d`)|Число с плавающей точкой небольшой точности|
|`DATE()`|Дата в формате ГГГГ-ММ-ДД|
|INT(size)|	Диапазон от -2 147 483 648 до 2 147 483 647|



К некоторых СУБД есть специальные типы данных. Подробнее можно посмотреть [здесь](https://sql-language.ru/osnova-sql/tipy-dannykh-sql.html).

**Комментарии**

В SQL есть комментарии
``` sql
-- это стандартный однострочный комментарий SQL
```
и
``` sql
/* многострочный комментарий
первая строка комметария
вторая строка комметария
 */
```

Команды SQL делятся на следующие группы:

**Определение данных**

|Команда|Комментарий|
|--:|:--|
|`CREATE TABLE` | Добавляет новую таблицу в базу данных|
|`DROP TABLE`   | Удаляет таблицу из базы данных|
|`ALTER TABLE`  | Изменяет структуру существующей таблицы|
|`CREATE VIEW` | Добавляет новое представление в базу данных|
|`DROP VIEW`   | Удаляет представление из базы данных|
|`CREATE INDEX` | Создает индекс для столбца|
|`DROP INDEX` | Удаляет индекс столбца|
|`CREATE SCHEMA` | Добавляет новую схему в базу данных|
|`DROP SCHEMA` | Удаляет схему из базы данных|
|`CREATE DOMAIN` | Добавляет новый домен значений данных|
|`ALTER DOMAIN`  | Изменяет определение домена|
|`DROP DOMAIN` | Удаляет домен из базы данных|

**Обработка данных**

|Команда|Комментарий|
|--:|:--|
|`SELECT` | Извлекает данные из базы данных|
|`INSERT` | Добавляет новые строки в базу данных|
|`UPDATE` | Обновляет данные, имеющиеся в базе данных|
|`MERGE` | Добавляет/обновляет/удаляет новые и старые строки на основе условий|
|`DELETE` | Удаляет строки из базы данных|

**Управление доступом**

|Команда|Комментарий|
|--:|:--|
|`GRANT` | Предоставляет пользователю привилегии доступа|
|`REVOKE` | Отменяет пользовательские привилегии доступа|
|`CREATE ROLE` | Добавляет в базу данных новую роль|
|`GRANT ROLE` | Предоставляет роль, содержащую привилегии доступа|
|`DROP ROLE` | Удаляет роль из базы данных|

**Управление транзакциями**

|Команда|Комментарий|
|--:|:--|
|`COMMIT` | Завершает текущую транзакцию|
|`ROLLBACK` | Отменяет текущую транзакцию|
|`SET TRANSACTION` | Определяет характеристики доступа к данным в текущей транзакции|
|`START TRANSACTION` | Явно начинает новую транзакцию|
|`SAVEPOINT`| Устанавливает точку восстановления транзакции|

**Работа с СУБД SQLite в Python**

Для работы с `SQLite` в `Python` используется модуль `sqlite3`.

`Python` поддерживает следующие типы данных `SQL`:

|Тип данных|Описание|
|--:|:--|
|`NULL`|Значение NULL|
|`INTEGER`|Целое число|
|`REAL`|Число с плавающей точкой|
|`TEXT`|Текст|
|`BLOB`|Бинарное представление крупных объектов|

Наиболее распространенные методы библиотеки `sqlite3`

|Команда|Комментарий|
|--:|:--|
|`connect()`|Метод для создания соединения с базой данных|
|`cursor()`|Метод для создания курсора -- объекта `Cursor`|
|`execute()`|Метод для выполнения одного выражения SQL|
|`executemany()`|Метод позволяет выполнить одно выражение SQL для последовательности параметров|
|`fetchone()`|Метод возвращает одну строку данных|
|`fetchall()`|Метод возвращает все строки в виде списка|
|`commit()`|Метод применяет изменения к БД|


Примечание: объект `Cursor` -- это основной способ работы с БД.  Создается курсор из соединения с БД.

Подробное описание библиотеки можно найти [здесь](https://docs.python.org/3/library/sqlite3.html).

Общая схема работы

```python
import sqlite3 # подключение библиотеки
con = sqlite3.connect("bibl.db") # подключение к базе/ если не было, то будет создана
cur = con.cursor() # задание курсора БД
cur.execute(...) #выполнение запросов
cur.close() #закрытие БД
```

In [1]:
import sqlite3 # подключение библиотеки
con = sqlite3.connect("bibl.db") # подключение к базе/ если не было, то будет создана
cur = con.cursor() # задание курсора БД
cur.execute()
cur.f
cur.close() #закрытие БД

Создание таблиц

Инструкция
```sql
CREATE TABLE table_name (
    column1 datatype,
    column2 datatype,
    column3 datatype,
   ....
);
```

In [ ]:
import sqlite3

In [5]:
con = sqlite3.connect("bibl.db") # подключение к базе/ если не было, то будет создана
cur = con.cursor() # задание курсора БД

In [3]:
create_table = """
CREATE TABLE authors(author_id TEXT not NULL primary key,
                      first_name TEXT,
                      last_name TEXT,
                      age INTEGER,
                      raiting REAL);
"""

In [4]:
cur.execute(create_table)
con.commit()

In [ ]:
#Просмотр таблиц
answer = """
SELECT name
FROM sqlite_master;
"""
cur.execute(answer).fetchall()

[('authors',), ('sqlite_autoindex_authors_1',)]

**Просмотр информации о таблице**

In [ ]:
querty_show_info_table = """
PRAGMA table_info('authors')
"""
res = cur.execute(querty_show_info_table)
res.fetchall()

[(0, 'author_id', 'TEXT', 1, None, 1),
 (1, 'first_name', 'TEXT', 0, None, 0),
 (2, 'last_name', 'TEXT', 0, None, 0),
 (3, 'age', 'INTEGER', 0, None, 0),
 (4, 'raiting', 'REAL', 0, None, 0)]

**Добавление данных**

Инструкция
```sql
INSERT INTO таблица(поле1, поле2)
VALUES (значение1, значение2);
```

In [6]:
#добавление одной записи
cur.execute("""
INSERT INTO authors(author_id, first_name, last_name, age, raiting)
VALUES('petrov_56', 'Петров', 'И.И.', 56, 6.7);
""")
#con.commit()

DatabaseError: ignored

In [ ]:
q = """
SELECT *
FROM authors;
"""

In [ ]:
res = cur.execute(q)

In [ ]:
res.fetchone()

('petrov_56', 'Петров', 'И.И.', 56, 6.7)

In [ ]:
#добавление нескольких записей

cur.execute("""INSERT INTO authors(author_id, first_name, last_name, age, raiting)
VALUES('ivanov_27', 'Иванов', 'П.П.', 27, 5.7),
      ('sidorov_45', 'Сидоров', 'И.П.', 45, 10);
""")
con.commit()

In [ ]:
q = """
SELECT *
    FROM authors
"""
res = cur.execute(q)
res.fetchall()

[('petrov_56', 'Петров', 'И.И.', 56, 6.7),
 ('ivanov_27', 'Иванов', 'П.П.', 27, 5.7),
 ('sidorov_45', 'Сидоров', 'И.П.', 45, 10.0)]

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_sql(q, con = con)

    author_id first_name last_name  age  raiting
0   petrov_56     Петров      И.И.   56      6.7
1   ivanov_27     Иванов      П.П.   27      5.7
2  sidorov_45    Сидоров      И.П.   45     10.0

In [ ]:
cur.close()

In [ ]:
con.close()

**Удаление данных**

Инструкция
```sql
DELETE FROM <имя таблицы >
[WHERE <предикат>];
```

In [ ]:
sql_delete_query = """
DELETE
 FROM authors
WHERE age < 30;
"""
cur.execute(sql_delete_query)
con.commit()

**Обновление данных**

Инструкция

```sql
UPDATE table_name
SET column1 = value1, column2 = value2, ...
WHERE condition;
```

In [ ]:
sqlite_update_query = """
Update authors set age = ?, first_name = ? where author_id = ?"""
records_to_update = [(44, 'Пантелев', 'petrov_56'), (78, 'Филимонов', 'ivanov_27'), (84, 'Кочергин', 'sidorov_45')]
cur.executemany(sqlite_update_query, records_to_update)
con.commit()

In [ ]:
q = """
SELECT *
    FROM authors
"""
res = cur.execute(q)
res.fetchall()

[('petrov_56', 'Пантелев', 'И.И.', 44, 6.7),
 ('ivanov_27', 'Филимонов', 'П.П.', 78, 5.7),
 ('sidorov_45', 'Кочергин', 'И.П.', 84, 10.0)]

## Выборка данных из одной таблицы

### Просмотр информации о таблицах БД

Каждая база данных `SQLite` имеет таблицу `sqlite_master`, которая содержит все остальные таблицы. Таблица `sqlite_master` имеет [следующую структуру](https://habr.com/ru/post/223451/)

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=15rAr5_zhErv6g21LOIwdRxI9U0_O0LJP' width="600" height="350" />
<figcaption>Структура таблицы `sqlite_master`</figcaption></center>
</figure>

Для таблиц поле `type` всегда будет `table`, а поле `name` будет именем таблицы. Итак, чтобы получить список всех таблиц в базе данных, следует использовать следующий запрос:

```sql
SELECT name FROM sqlite_master
WHERE type='table'
ORDER BY name;
```

Просмотр информации о таблице

Инструкция
```sql
PRAGMA table_info('name_table')
```

Она возвращает одну строку для каждого столбца.
Столбцы в результирующем наборе включают
- имя столбца,
- тип данных,
- может ли столбец иметь значение NULL,
- значение по умолчанию для столбца.

Столбец "pk" в результирующем наборе равен нулю для столбцов, которые не являются частью первичного ключа, и является индексом столбца в первичном ключе для столбцов, которые являются частью первичного ключа.

In [8]:
import sqlite3
import pandas as pd

In [9]:
#подключение к существующей БД
con = sqlite3.connect('banki.db')
cur = con.cursor()

In [11]:
#создание новой БД
# con = sqlite3.connect('banki_new.db')
# cur = con.cursor()
# con.close()

In [12]:
request_info = """
SELECT name FROM sqlite_master
WHERE type='table'
ORDER BY name;
"""

In [13]:
res = cur.execute(request_info)

In [14]:
res.fetchall()

[('clients_churn',)]

In [15]:
inf_table = """
PRAGMA table_info('clients_churn')
"""

In [16]:
cur.execute(inf_table).fetchall()

[(0, 'user_id', 'INTEGER', 0, None, 1),
 (1, 'score', 'INTEGER', 0, None, 0),
 (2, 'city', 'TEXT', 0, None, 0),
 (3, 'gender', 'TEXT', 0, None, 0),
 (4, 'age', 'INTEGER', 0, None, 0),
 (5, 'objects', 'INTEGER', 0, None, 0),
 (6, 'balance', 'REAL', 0, None, 0),
 (7, 'products', 'INTEGER', 0, None, 0),
 (8, 'credit_card', 'INTEGER', 0, None, 0),
 (9, 'loyalty', 'INTEGER', 0, None, 0),
 (10, 'estimated_salary', 'REAL', 0, None, 0),
 (11, 'churn', 'INTEGER', 0, None, 0)]

**Выборка данных**

Инструкция
```sql
SELECT [DISTINCT | ALL] поля_таблиц
FROM список_таблиц
[WHERE условия_на_ограничения_строк]
[GROUP BY условия_группировки]
[HAVING условия_на_ограничения_строк_после_группировки]
[ORDER BY порядок_сортировки [ASC | DESC]]
[LIMIT ограничение_количества_записей]
```
Обязательными являются два предложения
```sql
SELECT [DISTINCT | ALL] поля_таблиц
FROM список_таблиц
```
Описание параметров запроса

|Параметр|Комментарий|
|--:|:--|
|`SELECT`| Определяет, какие из всех возможных столбцов следует включить в результирующий набор запроса|
|`DISTINCT` | Используется для исключения повторяющихся строк из результата|
|`ALL` или `*` (по умолчанию) | Используется для получения всех данных, в том числе и повторений|
|`FROM` | Перечисляются используемые в запросе таблицы из базы данных|
| `WHERE` | Условный оператор, который используется для ограничения строк по какому-либо условию|
|`GROUP BY`| Используется для группировки строк|
| `HAVING` |  Применяется после группировки строк для фильтрации по значениям агрегатных функций|
|`ORDER BY`| Используется для сортировки. У него есть два параметра: `ASC` (по умолчанию) сортировка по возрастанию; `DESC` — по убыванию|
|`LIMIT`|Используется для ограничения количества строк для вывода|

Порядок выполнения предложений инструкции:
- FROM;
- WHERE;
- GROUP BY;
- HAVING;
- SELECT;
- DISTINCT;
- ORDER BY.

Задание:
- вывести все поля таблицы;
- вывести первых 10 строк таблицы;
- выбрать столбцы `user_id`, `city`, `gender`, `age` и `churn`.

In [17]:
# подключение библиотеки
import sqlite3
import pandas as pd

In [18]:
# подключение в существующей базе данных
con = sqlite3.connect('banki.db')
cur = con.cursor()

In [19]:
# вывести все поля таблицы;
req1 = cur.execute("""
SeLECT *
FROM clients_churn;
""")

type(req1.fetchall())


req2 = """
SELECT *
FROM clients_churn;
"""

pd.read_sql(req2, con=con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608437,698,Город_Р,Ж,39,9,161993.89,1,0,0,90212.38,0
1,15608442,612,Город_Р,М,35,1,NaN,1,1,1,83256.26,1
2,15608450,601,Город_Я,М,47,1,64430.06,2,0,1,96517.97,0
3,15608515,627,Город_В,Ж,30,6,57809.32,1,1,0,188258.49,0
4,15608532,745,Город_В,М,48,10,96048.55,1,1,0,74510.65,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15858364,711,Город_Я,Ж,37,8,113899.92,1,0,0,80215.20,0
9996,15858381,481,Город_Я,М,37,8,152303.66,2,1,1,175082.20,0
9997,15858392,541,Город_В,Ж,39,9,100116.67,1,1,1,199808.10,1
9998,15858396,758,Город_Я,Ж,34,1,154139.45,1,1,1,60728.89,0
9999,15858426,614,Город_Р,Ж,40,3,113348.50,1,1,1,77789.01,0

In [20]:
# вывести первых 10 строк таблицы;
# выбрать столбцы user_id, city, gender, age и churn.


req3 = """
SELECT *
FROM clients_churn
LIMIT 10;
"""

req4 = """
SELECT user_id,
       city,
       gender,
       age,
       churn
FROM clients_churn
LIMIT 10;
"""

pd.read_sql(req3, con=con)
pd.read_sql(req4, con=con).head(15)

    user_id     city gender  age  churn
0  15608437  Город_Р      Ж   39      0
1  15608442  Город_Р      М   35      1
2  15608450  Город_Я      М   47      0
3  15608515  Город_В      Ж   30      0
4  15608532  Город_В      М   48      0
5  15608542  Город_Я      М   38      0
6  15608614  Город_Р      М   29      0
7  15608615  Город_Я      Ж   28      0
8  15608627  Город_Я      М   39      0
9  15608732  Город_Я      М   44      0

In [ ]:
res = cur.execute(show_all)
res.fetchall()

[(15608437, 698, 'Город_Р', 'Ж', 39, 9, 161993.89, 1, 0, 0, 90212.38, 0),
 (15608442, 612, 'Город_Р', 'М', 35, 1, None, 1, 1, 1, 83256.26, 1),
 (15608450, 601, 'Город_Я', 'М', 47, 1, 64430.06, 2, 0, 1, 96517.97, 0),
 (15608515, 627, 'Город_В', 'Ж', 30, 6, 57809.32, 1, 1, 0, 188258.49, 0),
 (15608532, 745, 'Город_В', 'М', 48, 10, 96048.55, 1, 1, 0, 74510.65, 0),
 (15608542, 532, 'Город_Я', 'М', 38, 9, None, 2, 0, 0, 30583.95, 0),
 (15608614, 631, 'Город_Р', 'М', 29, 3, None, 2, 1, 1, 197963.46, 0),
 (15608615, 845, 'Город_Я', 'Ж', 28, 9, None, 2, 1, 1, 56185.98, 0),
 (15608627, 709, 'Город_Я', 'М', 39, 8, None, 2, 1, 0, 56214.09, 0),
 (15608732, 653, 'Город_Я', 'М', 44, 8, None, 2, 1, 1, 154639.72, 0)]

In [ ]:
show_only_more = """
SELECT user_id,
       city,
       gender,
       age,
       churn
FROM clients_churn
LIMIT 10; -- указываем число выводимых записей
"""

pd.read_sql(show_only_more, con)

    user_id     city gender  age  churn
0  15608437  Город_Р      Ж   39      0
1  15608442  Город_Р      М   35      1
2  15608450  Город_Я      М   47      0
3  15608515  Город_В      Ж   30      0
4  15608532  Город_В      М   48      0
5  15608542  Город_Я      М   38      0
6  15608614  Город_Р      М   29      0
7  15608615  Город_Я      Ж   28      0
8  15608627  Город_Я      М   39      0
9  15608732  Город_Я      М   44      0

**Псевдонимы столбцов**

В таблице, являющейся результатом запроса, может потребоваться изменить заголовок столбца (некорретное или длинное название, или название, генерируемое встроенными функциями). Это можно сделать следующей инструкцией:
```sql
SELECT
    Column_Name1 AS New_Column_Name,
    Column_Name2 AS New_Column_Name
 FROM Table_Name;
```

Задание:
- вывести столбцы с новыми именами: score -> балл, city -> город.

In [31]:
# Ваш код здесь

req5 = """
SELECT cc.user_id AS идентификатор_пользователя,
       city AS город,
       gender,
       age возраст,
       churn
FROM clients_churn cc
LIMIT 10;
"""


req6 = """
SELECT user_id,
       city AS город,
       gender,
       age возраст,
       churn
FROM clients_churn cc
LIMIT 10;
"""


pd.read_sql(req6, con=con)

    user_id    город gender  возраст  churn
0  15608437  Город_Р      Ж       39      0
1  15608442  Город_Р      М       35      1
2  15608450  Город_Я      М       47      0
3  15608515  Город_В      Ж       30      0
4  15608532  Город_В      М       48      0
5  15608542  Город_Я      М       38      0
6  15608614  Город_Р      М       29      0
7  15608615  Город_Я      Ж       28      0
8  15608627  Город_Я      М       39      0
9  15608732  Город_Я      М       44      0

**Просмотр уникальных значений**

Оператор `DISTINCT` используется для удаления дубликатов из результирующего набора. Предложение `DISTINCT` может использоваться только в запросе `SELECT`.

Инструкция
``` sql
SELECT DISTINCT expressions
FROM tables;
```

Задание:
- вывести уникальные значения столбцов `city` и `gender`.

In [36]:
# Ваш код здесь

req7 = """
SELECT DISTINCT city, gender /*это пример комментария*/
FROM clients_churn AS cc;
"""

pd.read_sql(req7,con=con)

      city gender
0  Город_Р      Ж
1  Город_Р      М
2  Город_Я      М
3  Город_В      Ж
4  Город_В      М
5  Город_Я      Ж

**Количество значений в группе**

Функция `COUNT` возвращает количество элементов в группе.

Задание:
- подсчитать количество строк в таблице;
- подсчитать количество уникальных значений для столбца `age`.

In [44]:
#Ваш код здесь
req8 = """
SELECT COUNT(*) общее_количество_строк
FROM clients_churn AS cc;
"""
pd.read_sql(req8,con=con)


#количество уникальных значений для двух признаков
req9 = """
SELECT COUNT(DISTINCT age),
       COUNT(DISTINCT city)
FROM clients_churn AS cc;
"""
pd.read_sql(req9, con=con)

   COUNT(DISTINCT age)  COUNT(DISTINCT city)
0                   70                     3

In [4]:
#Ваш код здесь

**Вычисляемые столбцы**

Кроме столбцов, значения которых извлекаются непосредственно из базы данных, SQL-зaпpoc на выборку может содержать вычисляемые столбцы, значения которых определяются на основании значений, хранящихся в базе данных. Чтобы получить вычисляемый столбец, в списке возвращаемых столбцов необходимо указать выражение. Выражение может включать имена столбцов, константы, знаки операций, встроенные функции.

**Встроенные функции**

Список встроенных функций в зависимости от СУБД можно посмотреть [здесь](https://oracleplsql.ru/sqlite-manual.html).

|Функция|Комментарий|
|--:|:--|
| `ABS` | Функция возвращает абсолютное значение числа|
| `AVG` | SQLite функция avg возвращает среднее значение выражения|
| `COUNT` | SQLite функция count возвращает количество выражений|
| `MAX` | SQLite функция max возвращает максимальное значение выражения|
| `MIN` | SQLite функция min возвращает минимальное значение выражения|
| `ROUND` | SQLite функция round возвращает число, округленное до определенного количества десятичных знаков|
| `SUM` | SQLite функция sum возвращает суммированное значение выражения |

Задание:
- подсчитать количество строк в таблице;
- подсчитать количество уникальных значений для столбца `age`.
- создать новый столбец `nalog`, значения которого рассчитываются по следующей формуле:
$$
nalog = 0.13*estimated\_salary
$$
- найти минимальное, максимальное и выборочное среднее по столбцу `estimated_salary`

In [49]:
# Ваш код здесь
req10 = """
SELECT ROUND(estimated_salary, 2) зп,
       ROUND(0.13*estimated_salary,2) AS налог
FROM clients_churn AS cc;
"""
pd.read_sql(req10, con=con)

req11 = """
SELECT MIN(estimated_salary),
       MAX(estimated_salary),
       AVG(estimated_salary)
FROM clients_churn AS cc;
"""
pd.read_sql(req11, con=con)

   MIN(estimated_salary)  MAX(estimated_salary)  AVG(estimated_salary)
0                  11.58              199992.48          100090.239881

**Отбор строк**

Достаточно часто требуется выбрать из таблицы и включить в результаты запроса только несколько строк. Для того, чтобы указать, какие строки нужно отобрать, используется предложение `WHERE`.

Инструкция
```sql
SELECT [DISTINCT | ALL] поля_таблиц
FROM список_таблиц
[WHERE условия_на_ограничения_строк]
```

Выделяют следующие пять основных условий отбора:
- Сравнение. Значение одного выражения сравнивается со значением другого
выражения;
- Проверка на принадлежность диапазону. Проверяется, попадает ли указанное
значение в определенный диапазон значений;
- Проверка наличия во множестве. Проверяется, совпадает ли значение выражения
с одним из значений из заданного множества;
- Проверка на соответствие шаблону. Проверяется, соответствует ли строковое
значение, содержащееся в столбце, определенному шаблону;
- Проверка на равенство значению NULL. Проверяется, содержится ли
в столбце значение NULL.

**Операторы сравнения**

|Оператор|Комментарий|
|--:|:--|
| `=`   | Равно|
| `<>`  | Не равно|
| `!=`  | Не равно|
| `>`   | Больше|
| `>=`	| Больше или равно|
| `<`   | Меньше|
| `<=`  | Меньше или равно|
| `!>`	| Не больше |
|  `!< `| Не меньше |

При составлении условия выбора могут использоваться логические операторы.

|Оператор|Комментарий|
|--:|:--|
| `AND` | Логический оператор `и`
| `OR`	| Логический оператор `или`|
| `NOT` | Отрицание условия |

Задание: Вывести список клиентов банка, проживающих в `Город_Р и имеющих доход больше 20000.

In [52]:
# Ваш код здесь

req12 = """
SELECT *
FROM clients_churn AS cc
WHERE (city = 'Город_Р')
      AND (estimated_salary>=20000);
"""
pd.read_sql(req12, con=con)

#псевдонимы можно использовать далее в запросе
req13 = """
SELECT city город,
       estimated_salary зп
FROM clients_churn AS cc
WHERE (город = 'Город_Р')
      AND (зп>=20000);
"""
pd.read_sql(req13, con=con)

,город,зп,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,Город_Р,90212.38,15608437,698,Город_Р,Ж,39,9,161993.89,1,0,0,90212.38,0
1,Город_Р,83256.26,15608442,612,Город_Р,М,35,1,NaN,1,1,1,83256.26,1
2,Город_Р,197963.46,15608614,631,Город_Р,М,29,3,NaN,2,1,1,197963.46,0
3,Город_Р,94739.20,15608827,545,Город_Р,Ж,32,4,NaN,1,1,0,94739.20,0
4,Город_Р,71709.12,15609028,574,Город_Р,М,36,1,NaN,2,0,1,71709.12,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2207,Город_Р,117431.10,15858100,736,Город_Р,Ж,28,2,NaN,2,1,1,117431.10,0
2208,Город_Р,74028.36,15858156,808,Город_Р,М,47,8,139196.00,1,0,1,74028.36,0
2209,Город_Р,54947.51,15858179,527,Город_Р,Ж,46,10,131414.76,1,1,0,54947.51,0
2210,Город_Р,93736.69,15858270,505,Город_Р,М,37,0,134006.39,1,1,1,93736.69,0
2211,Город_Р,77789.01,15858426,614,Город_Р,Ж,40,3,113348.50,1,1,1,77789.01,0

**Проверка на принадлежность диапазону**

Условие `BETWEEN ... AND` используется для извлечения значений диапазона.

Инструкция
```sql
SELECT [DISTINCT | ALL] поля_таблиц
FROM список_таблиц
[WHERE столбец или выражение BETWEEN нижняя_граница AND верхняя_граница;]
```

<u>Замечание</u>. При проверке на принадлежность диапазону верхняя и нижняя границы считаются частью диапазона.

Задание: Вывести список клиентов банка, проживающих в `Город_Р` в возрасте от 35 до 50 лет.

In [56]:
# Ваш код здесь
show_when_1 = """
SELECT *
FROM clients_churn
WHERE (city = 'Город_Р') AND
      (age BETWEEN 35 AND 50);
"""
pd.read_sql(show_when_1, con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608437,698,Город_Р,Ж,39,9,161993.89,1,0,0,90212.38,0
1,15608442,612,Город_Р,М,35,1,NaN,1,1,1,83256.26,1
2,15609028,574,Город_Р,М,36,1,NaN,2,0,1,71709.12,0
3,15609048,660,Город_Р,Ж,42,5,NaN,3,1,1,189016.24,1
4,15609279,573,Город_Р,М,44,9,NaN,2,1,0,107124.17,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1279,15857867,617,Город_Р,Ж,36,7,115617.24,1,1,1,71519.40,0
1280,15858156,808,Город_Р,М,47,8,139196.00,1,0,1,74028.36,0
1281,15858179,527,Город_Р,Ж,46,10,131414.76,1,1,0,54947.51,0
1282,15858270,505,Город_Р,М,37,0,134006.39,1,1,1,93736.69,0
1283,15858426,614,Город_Р,Ж,40,3,113348.50,1,1,1,77789.01,0

**Проверка наличия во множестве**

Распространенным условием отбора является проверка на наличие во множестве. Для этого применяется оператор `IN`. В `SQLite` опертор `IN` используется для уменьшения необходимости использования нескольких условий `OR`.

Инструкция
```sql
SELECT [DISTINCT | ALL] поля_таблиц
FROM список_таблиц
[WHERE столбец IN (value1, value2, .... value_n);]
```

Задание: Вывести список клиентов банка, проживающих в `Город_Р` и в возрасте либо 35, либо 50 лет.

In [57]:
# Ваш код здесь
show_when_2 = """
SELECT *
FROM clients_churn
WHERE (city = 'Город_Р') AND
      (age IN (35, 50));
"""
pd.read_sql(show_when_2, con)


show_when_3 = """
SELECT *
FROM clients_churn
WHERE (city = 'Город_Р') AND
      ((age = 35) OR (age = 50));
"""
pd.read_sql(show_when_3, con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608442,612,Город_Р,М,35,1,NaN,1,1,1,83256.26,1
1,15611923,680,Город_Р,М,35,9,NaN,2,0,0,143774.06,0
2,15612362,577,Город_Р,М,35,5,110080.30,1,1,1,109794.31,0
3,15614809,663,Город_Р,М,35,5,NaN,2,1,1,62634.94,0
4,15615528,535,Город_Р,М,35,8,118989.92,1,1,1,135536.72,0
...,...,...,...,...,...,...,...,...,...,...,...,...
158,15844956,599,Город_Р,М,35,6,137102.65,1,0,0,76870.81,0
159,15848426,694,Город_Р,Ж,35,7,NaN,1,1,0,133570.43,1
160,15853168,795,Город_Р,М,35,8,NaN,2,1,0,167155.36,0
161,15855653,653,Город_Р,М,35,6,116662.96,2,1,1,23864.21,0
162,15856158,781,Город_Р,М,35,4,80790.74,1,1,0,116429.51,0

In [58]:
# Ваш код здесь
show_when_3 = """
SELECT AVG(estimated_salary)
FROM clients_churn
WHERE (city IN ('Город_Р', 'Город_Я')) AND
      (age IN (35, 50));
"""
pd.read_sql(show_when_3, con)

   AVG(estimated_salary)
0           93544.671286

**Проверка на соответствие шаблону**

В `SQLite` для поиска строковых значений, удовлетворяющих некоторому шаблону, используется оператор `LIKE`.

Инструкция
```sql
SELECT [DISTINCT | ALL] поля_таблиц
FROM список_таблиц
[WHERE столбец LIKE шаблон;]
```

Для составления шаблона поиска необходимо использовать следующие подстановочные символы:

|Подстановочный символ|Пояснение|
|--:|:--|
| `%` | Соответствует любой строке любой длины (в том числе нулевой длины)|
|`_`  | Соответствует одному символу|

Подстановочные знаки можно помещать в любое место строки шаблона, и в одной строке может содержаться несколько подстановочных знаков.

*Управляющие символы*

Если присутствует необязательное предложение ESCAPE, выражение после ключевого слова ESCAPE должно содержать строку, состоящую из одного символа. Этот символ может использоваться в шаблоне LIKE для включения буквенного процента или символов подчеркивания. Экранирующий символ, сопровождаемый символом процента (%), подчеркиванием (_) или вторым экземпляром самого экранирующего символа, соответствует буквальному символу процента, подчеркиванию или одному escape-символу соответственно.

In [65]:
# Ваш код здесь

show_when_4 = """
SELECT *
FROM clients_churn
WHERE city LIKE "%__Я"; --%_Я
"""
pd.read_sql(show_when_4, con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608450,601,Город_Я,М,47,1,64430.06,2,0,1,96517.97,0
1,15608542,532,Город_Я,М,38,9,NaN,2,0,0,30583.95,0
2,15608615,845,Город_Я,Ж,28,9,NaN,2,1,1,56185.98,0
3,15608627,709,Город_Я,М,39,8,NaN,2,1,0,56214.09,0
4,15608732,653,Город_Я,М,44,8,NaN,2,1,1,154639.72,0
...,...,...,...,...,...,...,...,...,...,...,...,...
5009,15858351,681,Город_Я,М,36,5,141952.07,1,1,1,185144.08,0
5010,15858362,640,Город_Я,М,63,2,68432.45,2,1,1,112503.24,1
5011,15858364,711,Город_Я,Ж,37,8,113899.92,1,0,0,80215.20,0
5012,15858381,481,Город_Я,М,37,8,152303.66,2,1,1,175082.20,0
5013,15858396,758,Город_Я,Ж,34,1,154139.45,1,1,1,60728.89,0

In [78]:
city = "'Город_Р', 'Город_Я'"

show_when_3 = f"""
SELECT *
FROM clients_churn
WHERE (city in ({city})) AND  ((age = 35) OR (age = 50));"""
pd.read_sql(show_when_3, con)
#show_when_3

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608442,612,Город_Р,М,35,1,NaN,1,1,1,83256.26,1
1,15609850,430,Город_Я,М,35,1,118894.22,1,0,0,2923.61,0
2,15611223,712,Город_Я,М,35,7,124616.23,1,1,1,69320.97,0
3,15611923,680,Город_Р,М,35,9,NaN,2,0,0,143774.06,0
4,15612187,463,Город_Я,М,35,2,101257.16,1,1,1,118113.64,0
...,...,...,...,...,...,...,...,...,...,...,...,...
446,15853680,586,Город_Я,Ж,35,7,NaN,2,1,0,70760.69,0
447,15853863,521,Город_Я,М,35,6,96423.84,1,1,0,10488.44,0
448,15855653,653,Город_Р,М,35,6,116662.96,2,1,1,23864.21,0
449,15856158,781,Город_Р,М,35,4,80790.74,1,1,0,116429.51,0
450,15858052,644,Город_Я,М,50,9,76817.00,4,1,0,196371.13,1

**Поиск значения NULL**

Значение `null` — это отсутствие значения. Для того, чтобы проверить, является ли выражение `null`, необходимо использовать оператор `is null`. Оператор `IS NOT NULL` проверят присвоено ли значение столбцу.

Инструкция
```sql
SELECT [DISTINCT | ALL] поля_таблиц
FROM список_таблиц
[WHERE столбец IS NULL;]
```

In [81]:
# Ваш код здесь

show_when_5 = """
SELECT *
FROM clients_churn
WHERE city IS NOT NULL;
"""
pd.read_sql(show_when_5, con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608437,698,Город_Р,Ж,39,9,161993.89,1,0,0,90212.38,0
1,15608442,612,Город_Р,М,35,1,NaN,1,1,1,83256.26,1
2,15608450,601,Город_Я,М,47,1,64430.06,2,0,1,96517.97,0
3,15608515,627,Город_В,Ж,30,6,57809.32,1,1,0,188258.49,0
4,15608532,745,Город_В,М,48,10,96048.55,1,1,0,74510.65,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,15858364,711,Город_Я,Ж,37,8,113899.92,1,0,0,80215.20,0
9996,15858381,481,Город_Я,М,37,8,152303.66,2,1,1,175082.20,0
9997,15858392,541,Город_В,Ж,39,9,100116.67,1,1,1,199808.10,1
9998,15858396,758,Город_Я,Ж,34,1,154139.45,1,1,1,60728.89,0
9999,15858426,614,Город_Р,Ж,40,3,113348.50,1,1,1,77789.01,0

In [ ]:
show_when_6 = """
SELECT *
FROM clients_churn
WHERE balance IS NULL;
"""
pd.read_sql(show_when_6, con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608442,612,Город_Р,М,35,1,None,1,1,1,83256.26,1
1,15608542,532,Город_Я,М,38,9,None,2,0,0,30583.95,0
2,15608614,631,Город_Р,М,29,3,None,2,1,1,197963.46,0
3,15608615,845,Город_Я,Ж,28,9,None,2,1,1,56185.98,0
4,15608627,709,Город_Я,М,39,8,None,2,1,0,56214.09,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3612,15857779,645,Город_Р,М,49,8,None,2,1,0,162012.60,0
3613,15857833,603,Город_Я,Ж,34,9,None,2,1,0,167916.35,0
3614,15857972,574,Город_Р,М,34,5,None,2,0,0,28269.86,0
3615,15857995,835,Город_Я,Ж,56,2,None,2,1,1,39820.13,0
3616,15858100,736,Город_Р,Ж,28,2,None,2,1,1,117431.10,0

**Сортировка результата запроса**

Строки результатов запроса, как и строки таблицы базы данных, не имеют определенного порядка. Включив в инструкцию `SELECT` предложение `ORDER ВY`, можно отсортировать результаты запроса.

Инструкция

```sql
SELECT [DISTINCT | ALL] поля_таблиц
FROM список_таблиц
[ORDER BY порядок_сортировки [ASC | DESC]]
```

По умолчанию `ORDER BY` выполняет сортировку по возрастанию. Чтобы управлять направлением сортировки вручную, после имени столбца указывается ключевое слово `ASC` (по возрастанию) или `DESC` (по убыванию).

Задание:
- выбрать значения признаков `city`, `age` и `balance` у клиентов, удовлетворяющих следующим условиям

$$
\left\{
\begin{array}{l}
\text{city} \in \{Город\_Р, Город\_Я\}, \\
\text{age} \in [18, 65],\\
\text{balance} \neq \text{NULL}.
\end{array}
\right.
$$

В итоговой таблице значения столбца `age` отсортировать по убыванию, а значения столбца `balance` по возрастанию.

In [ ]:
# Ваш код здесь
show_when_7 = """
SELECT *
FROM clients_churn
WHERE city IN ('Город_Р', 'Город_Я') AND
      (age BETWEEN 18 AND 65) AND
      (balance IS NOT NULL)
ORDER BY age ASC, balance DESC
LIMIT 50;
"""
pd.read_sql(show_when_7, con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15708063,706,Город_Я,М,18,2,176139.50,2,1,0,129654.22,0
1,15830355,844,Город_Я,М,18,2,160980.03,1,0,0,145936.28,0
2,15813045,656,Город_Я,М,18,10,151762.74,1,0,1,127014.32,0
3,15856187,677,Город_Р,М,18,8,134796.87,2,1,1,114858.90,0
4,15664629,727,Город_Я,М,18,4,133550.67,1,1,1,46941.41,0
5,15771565,509,Город_Я,М,18,7,102983.91,1,1,0,171770.58,0
6,15838967,681,Город_Я,Ж,18,1,98894.39,1,1,1,9596.40,0
7,15611914,570,Город_Я,Ж,18,4,82767.42,1,1,0,71811.90,0
8,15722979,792,Город_Я,М,19,7,143390.51,1,1,0,33282.84,0
9,15852727,756,Город_Р,М,19,4,130274.22,1,1,1,133535.29,0
10,15707375,645,Город_Я,М,19,9,128514.84,1,0,0,175969.19,0
11,15657981,660,Город_Я,М,19,5,127649.64,1,1,1,40368.65,0
12,15622628,708,Город_Р,М,19,7,112615.86,1,1,1,4491.77,0
13,15707798,696,Город_Я,М,19,1,110928.51,1,1,1,2766.63,0
14,15736683,614,Город_Я,Ж,19,5,97445.49,2,1,0,122823.34,0
15,15837577,739,Город_Р,М,19,5,89750.21,1,1,0,193008.52,0
16,15789400,463,Город_Р,М,20,8,204223.03,1,1,0,128268.39,0
17,15807658,596,Город_Р,М,20,3,187294.46,1,1,0,103456.47,0
18,15833060,660,Город_Я,Ж,20,6,167685.56,1,1,0,57929.90,0
19,15730743,703,Город_Р,М,20,3,165260.98,1,1,1,41626.78,0
20,15725259,762,Город_Я,М,20,1,139432.55,1,1,1,85606.83,0
21,15714536,688,Город_Я,М,20,8,137624.40,2,1,1,197582.79,0
22,15800809,655,Город_Я,Ж,20,7,134397.61,1,0,0,28029.54,0
23,15777501,739,Город_Я,Ж,20,4,133800.98,1,0,1,150245.81,0
24,15812651,643,Город_Р,Ж,20,0,133313.34,1,1,1,3965.69,0
25,15676576,781,Город_Я,М,20,0,125023.10,2,1,1,108301.45,0
26,15712018,636,Город_Я,Ж,20,10,124266.86,1,0,0,100566.81,0
27,15769431,601,Город_Р,Ж,20,9,122446.61,2,1,0,86791.90,0
28,15824241,685,Город_Я,М,20,4,104719.94,2,1,0,38691.34,0
29,15675635,662,Город_Р,М,20,9,104508.77,2,0,0,73107.53,0
30,15731720,595,Город_Я,М,20,4,95830.43,1,1,0,177738.98,0
31,15695410,539,Город_Я,М,20,0,83459.86,1,1,1,146752.67,0
32,15768396,676,Город_Я,М,20,1,80569.73,1,0,0,68621.98,0
33,15779156,596,Город_Я,М,21,4,210433.08,2,0,1,197297.77,1
34,15823697,735,Город_Я,Ж,21,1,178718.19,2,1,0,22388.00,0
35,15755639,499,Город_Я,Ж,21,3,176511.08,1,1,1,153920.22,0
36,15776982,746,Город_Я,Ж,21,8,166883.07,2,0,1,194563.65,0
37,15759961,544,Город_Я,Ж,21,10,161525.96,2,1,0,9262.77,0
38,15803510,519,Город_Я,Ж,21,1,146329.57,2,1,1,194867.27,0
39,15687698,745,Город_Я,М,21,4,137910.45,1,1,1,177235.23,0
40,15740342,637,Город_Я,Ж,21,10,125712.20,1,0,0,175072.47,0
41,15685648,618,Город_Я,Ж,21,2,125682.79,1,0,0,57762.00,0
42,15699443,720,Город_Р,М,21,2,123200.78,1,1,1,180712.28,0
43,15741783,674,Город_Я,Ж,21,9,120150.39,2,1,1,33964.03,0
44,15704827,570,Город_Р,М,21,7,116099.82,1,1,1,148087.62,0
45,15843439,485,Город_Р,Ж,21,5,113157.22,1,1,1,54141.50,0
46,15856063,710,Город_Я,М,21,4,109130.96,2,1,1,56191.99,0
47,15739275,613,Город_Я,Ж,21,7,105627.95,1,1,1,36560.51,0
48,15832450,691,Город_Р,М,21,3,103000.94,1,1,1,104648.58,0
49,15773532,627,Город_Я,Ж,21,7,98993.02,1,1,1,169156.64,0

**Группировка**

В `SQLite` оператор `GROUP BY` используется в запросе `SELECT` для сбора данных по нескольким записям и группировки результатов по одному или нескольким столбцам.

Запрос, включающий в себя предложение `GROUP ВY`, называется *запросом с группировкой*, поскольку он объединяет строки исходных таблиц в группы и для
каждой группы строк генерирует одну строку таблицы результатов запроса.

Столбцы, указанные в предложении `GROUP ВY`, называются *столбцами группировки*,
поскольку именно они определяют, по какому признаку строки делятся на
группы.

Инструкция
```sql

SELECT expression1, expression2, ... expression_n,
       aggregate_function (expression)
FROM tables
[WHERE conditions]
GROUP BY expression1, expression2, ... expression_n;
```
Здесь

- `expression1, expression2, ... expression_n` --- выражения, которые не заключены в агрегатную функцию и должны быть включены в предложение `GROUP BY`;
- `aggregate_function` --- такие функции, как функции `sum`, `count`, `min`, `max` или `avg`;
- `tables` --- таблицы, из которых необходимо получить записи. В операторе `FROM` должна быть указана хотя бы одна таблица.
- `WHERE conditions` --- необязательные условия, которые должны быть выполнены для выбранных записей.

Задание:
- в условиях предыдущей задачи рассчитать средний доход и возраст в каждом городе.

In [84]:
# Ваш код здесь
show_when_8 = """
SELECT AVG(estimated_salary) AS 'Средний доход',
       AVG(age) AS 'Средний возраст',
       city AS 'Город'
FROM clients_churn
WHERE city IN ('Город_Р', 'Город_Я') AND
      (age BETWEEN 18 AND 65) AND
      (balance IS NOT NULL)
GROUP BY city
"""
pd.read_sql(show_when_8, con)


show_when_9 = """
SELECT Median(balance)
FROM clients_churn
WHERE city IN ('Город_Р', 'Город_Я') AND
      (age BETWEEN 18 AND 65) AND
      (balance IS NOT NULL)
GROUP BY city
"""
pd.read_sql(show_when_9, con)

DatabaseError: ignored

In [94]:
# CASE
# IIF(условие, значение_условие_истинно, значение_условие_ложно)

# Ваш код здесь
show_when_8 = """
SELECT AVG(estimated_salary) AS 'Средний доход',
       AVG(age) AS 'Средний возраст',
       city AS 'Город',
       IIF(city='Город_В', 'Филиал_В', IIF(city='Город_Р', 'Филиал_Р', 'Филиал_Я')) as филиал
FROM clients_churn
WHERE (age BETWEEN 18 AND 65) AND
      (balance IS NOT NULL)
GROUP BY city
"""
pd.read_sql(show_when_8, con)

   Средний доход  Средний возраст    Город    филиал
0  101158.637963        38.943558  Город_В  Филиал_В
1   99947.031238        38.406752  Город_Р  Филиал_Р
2  100671.977609        37.820513  Город_Я  Филиал_Я

In [ ]:
# CASE
# IIF(условие, значение_условие_истинно, значение_условие_ложно)

# Ваш код здесь
show_when_8 = """
SELECT AVG(estimated_salary) AS 'Средний доход',
       AVG(age) AS 'Средний возраст',
       city AS 'Город',


FROM clients_churn
WHERE (age BETWEEN 18 AND 65) AND
      (balance IS NOT NULL)
GROUP BY city
"""
pd.read_sql(show_when_8, con)

In [107]:
# CASE
# IIF(условие, значение_условие_истинно, значение_условие_ложно)



# Ваш код здесь
show_when_8 = """
SELECT AVG(estimated_salary) AS 'Средний доход',
       AVG(age) AS 'Средний возраст',
       city AS 'Город',
       IIF(city='Город_В', 'Филиал_В', IIF(city='Город_Р', 'Филиал_Р', 'Филиал_Я')) as филиал
FROM clients_churn
WHERE (age BETWEEN 18 AND 65) &
      (balance IS NOT NULL)
GROUP BY city;
"""
pd.read_sql(show_when_8, con)


# Ваш код здесь
show_when_8 = """
SELECT AVG(estimated_salary) AS 'Средний доход',
       AVG(age) AS 'Средний возраст',
       city AS 'Город',
       CASE
            WHEN city='Город_В'
            THEN 'Филиал_В'
            WHEN city='Город_Р'
            THEN 'Филиал_Р'
            WHEN city='Город_Я'
            THEN 'Филиал_Я'
       END as филиал
FROM clients_churn
WHERE (age BETWEEN 18 AND 65) &
      (balance IS NOT NULL)
GROUP BY city;
"""
pd.read_sql(show_when_8, con)

   Средний доход  Средний возраст    Город    филиал
0  101158.637963        38.943558  Город_В  Филиал_В
1   99947.031238        38.406752  Город_Р  Филиал_Р
2  100671.977609        37.820513  Город_Я  Филиал_Я

**Оператор HAVING**

В `SQLite` оператор `HAVING` используется в сочетании с `GROUP BY`, чтобы ограничить группы возвращаемых строк только теми, чье условие `TRUE`.

Инструкция
```sql
SELECT expression1, expression2, ... expression_n,
       aggregate_function (aggregate_expression)
FROM tables
[WHERE conditions]
GROUP BY expression1, expression2, ... expression_n
HAVING condition;
```
Здесь
- `expression1, expression2, ... expression_n` --- выражения, которые не заключены в агрегатную функцию и должны быть включены в оператор `GROUP BY`;
- `aggregate_function` --- такие функции, как `sum`, `count`, `min`, `max` или `avg`;
- `aggregate_expression` --- столбец или выражение, для которого будет использоваться функция `aggregate_function`;
- `tables` --- таблицы, из которых вы хотите получить записи. В операторе `FROM` должна быть указана хотя бы одна таблица;
- `WHERE conditions` --- необязательные условия для выбора записей;
- `HAVING condition` --- это еще одно условие, применяемое только к агрегированным результатам, чтобы ограничить группы возвращаемых строк. Только те группы, состояние которых оценивается как `true`, будут включены в результирующий набор.

In [ ]:
# Ваш код здесь
querty_select_where_groupby_naving = """
SELECT city,
       ROUND(AVG(age), 2) AS mean_age,
       ROUND(AVG(estimated_salary), 2) AS mean_salary
FROM clients_churn
WHERE (balance IS NOT NULL) AND
      (age BETWEEN 18 AND 65) AND
      city IN ('Город_Р', 'Город_Я')
GROUP BY city
HAVING mean_age > 38
ORDER BY mean_age ASC;
"""

# Ваш код здесь
show_when_8 = """
SELECT AVG(estimated_salary) AS 'Средний доход',
       AVG(age) AS 'Средний возраст',
       city AS 'Город'
FROM clients_churn
WHERE city IN ('Город_Р', 'Город_Я') AND
      (age BETWEEN 18 AND 65) AND
      (balance IS NOT NULL)
GROUP BY city
HAVING AVG(age) > 38;
"""
pd.read_sql(show_when_8, con)

In [87]:
#найдем количество женщин-клиентов в каждом городе

show_when_8 = """
SELECT COUNT(user_id),
       city AS 'Город',
       churn
FROM clients_churn
WHERE gender = 'Ж'
GROUP BY city, churn
"""
pd.read_sql(show_when_8, con=con)

   COUNT(user_id)    Город  churn
0             745  Город_В      0
1             448  Город_В      1
2             858  Город_Р      0
3             231  Город_Р      1
4            1801  Город_Я      0
5             460  Город_Я      1

In [91]:
#con = sqlite.connect()
pd.read_sql(show_when_8, con)

   COUNT(user_id)    Город  churn
0             745  Город_В      0
1             448  Город_В      1
2             858  Город_Р      0
3             231  Город_Р      1
4            1801  Город_Я      0
5             460  Город_Я      1

**Подзапросы**

В `SQL` имеется возможность составления вложенных запросов или подзапросов. Обычно вложенным запросом или подзапросом является SQL предложение, начинающиеся с команды SELECT. Подзапрос — это запрос внутри запроса. Первый запрос называется внешним, второй запрос называется внутренним или вложенным.

В выражении SELECT подзапросы могут вводиться четырьмя способами [[источник]](https://metanit.com/sql/mysql/4.8.php):
- в условии в выражении `WHERE`;
- в условии в выражении `HAVING`;
- в качестве таблицы для выборки в выражении `FROM`;
- в качестве спецификации столбца в выражении `SELECT`.

Подзапрос всегда заключен в круглые скобки и выполняется перед
содержащей инструкцией. Подобно любому запросу, подзапрос возвращает
результирующий набор, который может состоять из:
- одной строки с одним столбцом;
- нескольких строк с одним столбцом;
- нескольких строк с несколькими столбцами.

Подзапросы часто используют в сочетании с операторами сравнения (`=`, `<>`, `<`, `>`, `<=`, `>=`).

Если подзапрос используется в условии равенства, но возвращает более
одной строки, то будет получено сообщение об ошибке.

Подзапросы с несколькими строками и одним столбцом:
- операторы `in` и `not in` позволяют проверить, входит ли конкретное значение в набор;
- оператор `all` позволяет сравнивать отдельное значение и каждое значение в наборе. Для создания соответствующего условия нужно использовать один из операторов сравнения (`=`, `<>`, `<`, `>`, `<=`, `>=`) в сочетании с оператором `all`.

Задание:
- вывести всех клиентов банка, проживающих в городах `Город_Я`, `Город_Р`;
- вывести всех клиентов банка, имеющих баланс выше среднего;
- вывести количество клиентов, проживающих в городах `Город_Я`, `Город_Р`.

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
con = sqlite3.connect('/content/banki.db')
cur = con.cursor()

In [ ]:
#Ваш код здесь
#вывести всех клиентов банка, проживающих в городах Город_Я, Город_Р;
request_1 = """
SELECT *
FROM (SELECT *
      FROM clients_churn
      WHERE city IN ('Город_Я', 'Город_Р'))
"""



pd.read_sql(request_1, con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608437,698,Город_Р,Ж,39,9,161993.89,1,0,0,90212.38,0
1,15608442,612,Город_Р,М,35,1,NaN,1,1,1,83256.26,1
2,15608450,601,Город_Я,М,47,1,64430.06,2,0,1,96517.97,0
3,15608542,532,Город_Я,М,38,9,NaN,2,0,0,30583.95,0
4,15608614,631,Город_Р,М,29,3,NaN,2,1,1,197963.46,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7486,15858362,640,Город_Я,М,63,2,68432.45,2,1,1,112503.24,1
7487,15858364,711,Город_Я,Ж,37,8,113899.92,1,0,0,80215.20,0
7488,15858381,481,Город_Я,М,37,8,152303.66,2,1,1,175082.20,0
7489,15858396,758,Город_Я,Ж,34,1,154139.45,1,1,1,60728.89,0
7490,15858426,614,Город_Р,Ж,40,3,113348.50,1,1,1,77789.01,0

In [ ]:
#вывести всех клиентов банка, имеющих баланс выше среднего
request_2 = """
SELECT *
FROM clients_churn
WHERE balance > ( SELECT AVG(balance)
                  FROM clients_churn
                  );
"""

pd.read_sql(request_2, con)

,user_id,score,city,gender,age,objects,balance,products,credit_card,loyalty,estimated_salary,churn
0,15608437,698,Город_Р,Ж,39,9,161993.89,1,0,0,90212.38,0
1,15608989,580,Город_В,М,44,9,143391.07,1,0,0,146891.07,1
2,15609031,761,Город_Я,Ж,33,6,138053.79,2,1,0,148779.41,0
3,15609114,515,Город_Я,М,48,5,129387.94,1,0,1,147955.91,1
4,15609203,683,Город_В,Ж,32,0,138171.10,2,1,1,188203.58,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3187,15858226,670,Город_В,М,40,2,164948.98,3,0,0,177028.00,1
3188,15858270,505,Город_Р,М,37,0,134006.39,1,1,1,93736.69,0
3189,15858351,681,Город_Я,М,36,5,141952.07,1,1,1,185144.08,0
3190,15858381,481,Город_Я,М,37,8,152303.66,2,1,1,175082.20,0
3191,15858396,758,Город_Я,Ж,34,1,154139.45,1,1,1,60728.89,0

In [ ]:
#вывести количество клиентов, проживающих в городах Город_Я, Город_Р

request_3 = """
SELECT city,
       COUNT(user_id) AS Количество_клиентов
FROM clients_churn
GROUP BY city
HAVING city IN (SELECT city
                FROM clients_churn
                WHERE city LIKE "%__Я" OR city LIKE "%__Р");
"""

pd.read_sql(request_3, con)

      city  Количество_клиентов
0  Город_Р                 2477
1  Город_Я                 5014

**Создание таблиц в базе данных по запросу SELECT**

Результаты запросов являются таблицами, которые можно сохранять и при необходимости обращаться к ним.

Создавать таблицы в `SQLite` можно различными способами, но любое предложение для создания таблицы в `SQLite` начинается с `CREATE TABLE`. Для создания  **временной таблицы** в базе данных `SQLite` необходимо использовать ключевое слово `TEMP` или `TEMPORARY`. Имена таблиц должны быть уникальны во всей базе данных.

Оператор `CREATE TABLE AS` используется для создания таблицы из существующей таблицы путем копирования столбцов существующей таблицы на основе оператора `SELECT`.

Инструкция:
``` sql
CREATE [`TEMP`или `TEMPORARY`] TABLE new_table AS
SELECT expressions
FROM existing_tables
[WHERE conditions];
```
Здесь:
- `table_name` --- имя создаваемой таблицы;
- `expressions` --- имена столбцов, которые нужно перенести из существующей таблицы в новую;
- `existing_tables` --- cуществующие таблицы, из которых можно скопировать определения столбцов и соответствующие записи (согласно оператору `WHERE`);
- `WHERE conditions` --- необязательные условия, которые должны быть выполнены для копирования записей в new_table.

Задание:
- создать постоянную и временную таблицы на основе запросов к таблице `clients_churn`.

In [111]:
request_3 = """
CREATE TABLE count_clients AS
SELECT city,
       COUNT(user_id) AS Количество_клиентов
FROM clients_churn
GROUP BY city
HAVING city IN (SELECT city
                FROM clients_churn
                WHERE city LIKE "%__Я" OR city LIKE "%__Р");
"""
cur.execute(request_3)
con.commit()

In [112]:
q = """
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;"""
pd.read_sql(q, con)

            name
0  clients_churn
1  count_clients

In [123]:
# Ваш код здесь

#создадим постоянную таблицу по запросу -- количество клиентов в двух городах

request_4 = """
CREATE TABLE count_client AS
SELECT city,
       COUNT(user_id) AS Количество_клиентов
FROM clients_churn
GROUP BY city
HAVING city IN (SELECT city
                FROM clients_churn
                WHERE city LIKE "%__Я" OR city LIKE "%__Р");
"""
cur.execute(request_4)
con.commit()
con.close()

In [124]:
con = sqlite3.connect('/content/banki.db')
cur = con.cursor()

In [125]:
q = """
SELECT name FROM sqlite_master
WHERE type='table'
ORDER BY name;
"""
pd.read_sql(q,con)

            name
0  clients_churn
1   count_client
2  count_clients

In [ ]:
#создадим временную таблицу по запросу -- количество клиентов в двух городах

request_5 = """
CREATE TEMP TABLE count_client_one_city AS
SELECT city,
       COUNT(user_id) AS Количество_клиентов
FROM clients_churn
GROUP BY city
HAVING city IN (SELECT city
                FROM clients_churn
                WHERE city LIKE "%__Я");
"""
cur.execute(request_5)

con.commit()

OperationalError: ignored

In [ ]:
pd.read_sql(q,con)

            name
0  clients_churn
1   count_client

In [129]:
querty_show_info_table = """
PRAGMA table_info('count_clients')
"""

pd.read_sql(querty_show_info_table, con)

   cid                 name  type  notnull dflt_value  pk
0    0                 city  TEXT        0       None   0
1    1  Количество_клиентов              0       None   0

In [127]:
cur.execute(querty_show_info_table).fetchall()

[(0, 'city', 'TEXT', 0, None, 0), (1, 'Количество_клиентов', '', 0, None, 0)]

In [117]:
request_4 = """
SELECT city,
       COUNT(user_id) AS Количество_клиентов
FROM clients_churn
GROUP BY city
HAVING city IN (SELECT city
                FROM clients_churn
                WHERE city LIKE "%__Я" OR city LIKE "%__Р");
"""
pd.read_sql(request_4, con)

      city  Количество_клиентов
0  Город_Р                 2477
1  Город_Я                 5014

In [116]:
pd.read_sql(querty_show_info_table, con)

    cid              name     type  notnull dflt_value  pk
0     0           user_id  INTEGER        0       None   1
1     1             score  INTEGER        0       None   0
2     2              city     TEXT        0       None   0
3     3            gender     TEXT        0       None   0
4     4               age  INTEGER        0       None   0
5     5           objects  INTEGER        0       None   0
6     6           balance     REAL        0       None   0
7     7          products  INTEGER        0       None   0
8     8       credit_card  INTEGER        0       None   0
9     9           loyalty  INTEGER        0       None   0
10   10  estimated_salary     REAL        0       None   0
11   11             churn  INTEGER        0       None   0

In [ ]:
request_6 = """
SELECT *
FROM count_client_one_city
"""
pd.read_sql(request_6, con)

      city  Количество_клиентов
0  Город_Я                 5014

**Удаление таблиц**

В `SQLite` оператор `DROP TABLE` позволяет удалить таблицу из базы данных.

Инструкция:
```sql
DROP TABLE [ IF EXISTS ] table_name
```
Здесь
- `table_name` --- имя таблицы для удаления из базы данных;
- `IF EXISTS` --- необязательный параметр. Если он указан, то оператор `DROP TABLE` не будет выдавать ошибку, если таблица не существует.

Задание:
- удалить созданную ранее постоянную таблицу.

In [ ]:
# Ваш код здесь


import pandas as pd
import sqlite3

In [ ]:
con = sqlite3.connect('/content/banki.db')
cur = con.cursor()

In [ ]:
con.close()

## Многотабличные запросы

**Структура БД**

Первичный ключ -- особенное поле в SQL-таблице, которое позволяет однозначно идентифицировать каждую запись в ней. Первичный ключ имеет несколько свойств:
- каждая запись в таком поле должна быть уникальной;
- запись в поле не должна быть пустой;
- в одной таблице может быть только один ключ (существуют также составные ключи, которые могут включать в себя несколько полей, однако здесь они не рассматриваются).

Внешний ключ нужен для того, чтобы связать две разные SQL-таблицы между собой. Внешний ключ таблицы должен соответствует значению первичного ключа таблицы, с которой он связан. Это помогает сохранять согласованность базы данных путем обеспечения так называемой «ссылочной целостности».


<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=160L6VoP2kz8mJfpFuLWF6_SdoVcvkT-J' width="400" height="400" />
<figcaption>Структура базы </figcaption></center>
</figure>

[Операция соединения](https://ru.wikipedia.org/wiki/%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D1%8F_(%D1%80%D0%B5%D0%BB%D1%8F%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B0)) -- одна из операций реляционной алгебры.

Исходными данными для операции являются два отношения и предикат (условие соединения). Результатом операции является отношение, логически получаемое как декартово произведение исходных отношений, к которому применена операция выборки (ограничения) с указанным предикатом (условием соединения).

In [ ]:
con = sqlite3.connect('/content/book_simple.db')
cur = con.cursor()

In [ ]:
# Реализовать декартово произведение двух таблиц

request_7 = """
SELECT category.title,
       publisher.name
FROM category, publisher
"""

pd.read_sql(request_7, con) #4 *218

                                               title          name
0                          Информационные технологии         Наука
1                            Математическая экономия         Наука
2    Теория вероятностей и математическая статистика         Наука
3                                Экономические науки         Наука
4                          Информационные технологии  Новое знание
..                                               ...           ...
867                              Экономические науки         ГПНТБ
868                        Информационные технологии          КГТУ
869                          Математическая экономия          КГТУ
870  Теория вероятностей и математическая статистика          КГТУ
871                              Экономические науки          КГТУ

[872 rows x 2 columns]

In [ ]:
# Ваш код здесь
request_8 = """
SELECT book.title,
       publisher.name
FROM book, publisher
WHERE publisher.name = 'Мир'
"""

pd.read_sql(request_8, con) #4 *218

                                             title name
0                        Информационные технологии  Мир
1                          Математическая экономия  Мир
2  Теория вероятностей и математическая статистика  Мир
3                              Экономические науки  Мир

**Соединение по равенству (неявное соединение)**


Среди многотабличных запросов наиболее распространены запросы к двум таблицам,
связанным с помощью естественного отношения <<предок-потомок>>. Таблица, содержащая **внешний ключ**, является <потомком>>, а таблица с **первичным
ключом** -- <<предком>>.

Для использования в запросе отношение <<предок-потомок>>, необходимо задать условие отбора, в котором первичный ключ сравнивается с внешним ключом.

Инструкция

```sql
SELECT columns_name
FROM table1, table2
WHERE table1.Primary_Key = table2.Foreign_Key
```

Задание:
- вывести наименование книг с издательствами.

In [ ]:
request_9 = """
SELECT book.title,
       publisher.name
FROM book, publisher
WHERE (publisher.id = book.publisher_id) AND (publisher.name = 'Наука')
"""

In [ ]:
pd.read_sql(request_9, con)

                                                 title   name
0                       Выбор вариантов: основы теории  Наука
1                        Введение в методы оптимизации  Наука
2    Нечеткие множества в моделях управления и иску...  Наука
3    Дискретные математические модели с приложениям...  Наука
4    Модели и методы управления организационными  с...  Наука
..                                                 ...    ...
147                             Геометрическая алгебра  Наука
148                    Решатели интеллектуальных задач  Наука
149               Теория игр и экономическое поведение  Наука
150        Теория графов: алгоритмы обработки деревьев  Наука
151             Когомологий бесконечномерных алгебр Ли  Наука

[152 rows x 2 columns]

Другие виды соединений (частные случаи соединения по равенству):
- внутреннее;
- внешнее;
- перекрестное.

**Оператор внутреннего соединения** `INNER JOIN` соединяет две таблицы. Порядок таблиц для оператора неважен, поскольку оператор является коммутативным.

Заголовок таблицы-результата является объединением (конкатенацией) заголовков соединяемых таблиц.

Тело результата логически формируется следующим образом:
1. Каждая строка одной таблицы сопоставляется с каждой строкой второй таблицы, после чего для полученной «соединённой» строки проверяется условие соединения (вычисляется предикат соединения).
2. Если условие истинно, в таблицу-результат добавляется соответствующая «соединённая» строка.

Внешнее соединение (OUTER JOIN) в отличие от (INNER JOIN) возвращает все строки одной или двух таблиц, которые участвуют в соединении. Выделяют: `LEFT OUTER JOIN`, `RIGHT OUTER JOIN` и `FULL OUTER JOIN`.

**Оператор левого внешнего соединения** `LEFT OUTER JOIN` соединяет две таблицы. Порядок таблиц для оператора важен, поскольку оператор не является коммутативным.

Заголовок таблицы-результата является объединением (конкатенацией) заголовков соединяемых таблиц.

Тело результата логически формируется следующим образом. Пусть выполняется соединение левой и правой таблиц по предикату (условию) `p`:
1. В результат включается внутреннее соединение (`INNER JOIN`) левой и правой таблиц по предикату `p`.
2. Затем в результат добавляются те строки левой таблицы, которые не вошли во внутреннее соединение на шаге 1. Для таких строк столбцы, соответствующие правой таблице, заполняются значениями `NULL`.

Инструкция
```sql
SELECT *
FROM
  -- Левая таблица
  LEFT OUTER JOIN
  -- Правая таблица
    ON -- = --
```


**Оператор правого внешнего соединения** `RIGHT OUTER JOIN` соединяет две таблицы. Порядок таблиц для оператора важен, поскольку оператор не является коммутативным.

Заголовок таблицы-результата является объединением (конкатенацией) заголовков соединяемых таблиц.

Тело результата логически формируется следующим образом. Пусть выполняется соединение левой и правой таблиц по предикату (условию) `p`:
1. В результат включается внутреннее соединение (`INNER JOIN`) левой и правой таблиц по предикату `p`.
2. Затем в результат добавляются те строки правой таблицы, которые не вошли во внутреннее соединение на шаге 1. Для таких строк столбцы, соответствующие левой таблице, заполняются значениями `NULL`.

Инструкция
``` sql
SELECT *
FROM
  -- Левая таблица
  RIGHT OUTER JOIN
  -- Правая таблица
    ON - = --
```


**Оператор полного внешнего соединения** `FULL OUTER JOIN` соединяет две таблицы. Порядок таблиц для оператора неважен, поскольку оператор является коммутативным.

Заголовок таблицы-результата является объединением (конкатенацией) заголовков соединяемых таблиц.

Тело результата логически формируется следующим образом. Пусть выполняется соединение первой и второй таблиц по предикату (условию) `p`. Слова «первой» и «второй» здесь не обозначают порядок в записи выражения (который неважен), а используются лишь для различения таблиц.
1. В результат включается внутреннее соединение (INNER JOIN) первой и второй таблиц по предикату p.
2. В результат добавляются те строки первой таблицы, которые не вошли во внутреннее соединение на шаге 1. Для таких строк столбцы, соответствующие второй таблице, заполняются значениями NULL.
3. В результат добавляются те строки второй таблицы, которые не вошли во внутреннее соединение на шаге 1. Для таких строк столбцы, соответствующие первой таблице, заполняются значениями NULL.

Инструкция
``` sql
SELECT *
FROM
  table1
  FULL OUTER JOIN
  table2
    ON -- = --
```

**Оператор `JOIN`**

В многостраничных запросах в предложении `FROM`, вместо списка таблиц, для описания операции соединения может использоваться ключевое слово `JOIN`, а связанные столбцы, использующиеся при соединении, указываются в предложении
`ON`, находящемся в конце предложения `FROM`.

Данный оператор объединяет данные из двух разных таблиц в базе. Цель использования оператора -- получить нужное подмножество данных.

Изначально JOIN --- бинарный оператор, то есть он работает с двумя переданными объектами. На практике современные реализации могут воспринимать и больше двух таблиц, просто операция в таком случае выполняется несколько раз.

Оператору передаются таблицы, которые нужно объединить, и критерий для объединения — логическое выражение, которое называется ключом. В процессе работы `JOIN` таблицы проверяются на соответствие этому критерию. Например, значение поля ID в одной таблице должно соответствовать полю ID в другом. Оператор проверит строки обеих таблиц и выберет пары строк, где ID совпадают.

Найденные результаты объединяются в одну таблицу. Две соответствующие друг другу разные строки преобразуются в одну — это важнейшее условие работы `JOIN`. Строки чаще всего из разных таблиц, но это не обязательно. Главная особенность `JOIN` — объединение двух объектов в один.

В `SQLite` `JOINS` используются для извлечения данных из нескольких таблиц. `SQLite` `JOIN` выполняется всякий раз, когда две или более таблицы объединяются в операторе `SQL.
Существуют различные типы `SQLite` JOIN`:
- INNER JOIN (простое соединение);
- LEFT OUTER JOIN (LEFT JOIN)
- CROSS JOIN

Замечание. В SQLite не поддерживаются RIGHT OUTER JOIN и FULL OUTER JOIN.

**INNER JOIN** (Простое соединение)
**SQLite INNER JOIN** это самый распространенный тип объединения. **SQLite INNER JOINS** возвращают все строки из нескольких таблиц, где выполняется условие соединения.

Инструкция
```sql
SELECT columns
FROM table1
INNER JOIN table2
ON table1.column = table2.column;
```

```sql
querty_union_where = """
SELECT book.title,
       publisher.name,
       category.title
FROM book, publisher, category
WHERE (book.publisher_id = publisher.id) AND
      (publisher.name IN ('Мир', 'МИР')) AND
      (book.category_id = category.id)
"""
```

```sql
querty_inner_join = """
SELECT book.title AS book_title,
       publisher.name AS publisher_name
FROM book
INNER JOIN publisher
ON book.publisher_id = publisher.id;
"""
```



**LEFT OUTER JOIN**
Другой тип объединения `SQLite` называется `LEFT OUTER JOIN`. Этот тип соединения возвращает все строки из таблиц с левосторонним соединением, указанным в условии `ON`, и только те строки из другой таблицы, где объединяемые поля равны (выполняется условие объединения).

Инструкция
```sql
SELECT columns
 FROM table1
 LEFT [OUTER] JOIN table2
   ON table1.column = table2.column;
```

**CROSS JOIN**
Другой тип SQLite объединения называется CROSS JOIN. Этот тип объединения возвращает комбинированный результирующий набор с каждой строкой из первой таблицы, сопоставленной с каждой строкой из второй таблицы. Это также называется декартовым произведением.

```sql
SELECT columns
FROM table1
CROSS JOIN table2;
```

In [ ]:
# Выведите список книг, выпущенных в издательстве "Мир".

request_10 = """
SELECT book.title,
       publisher.name
FROM book
INNER JOIN publisher
ON book.publisher_id = publisher.id
"""

In [ ]:
pd.read_sql(request_10, con)

                                                 title             name
0                       Выбор вариантов: основы теории            Наука
1                                 Экономический анализ     Новое знание
2              Имитационное моделирование. Классика CS              BHV
3                              Математическая экономия              ИИЛ
4    Управление производством при нечеткой исходной...  Энергоатомиздат
..                                                 ...              ...
821        Теория графов: алгоритмы обработки деревьев            Наука
822                  Микроэкономика. Принципы и анализ              АНХ
823  Проектирование интегрированных систем библиоте...            ГПНТБ
824                    Экономико-математические методы             КГТУ
825             Когомологий бесконечномерных алгебр Ли            Наука

[826 rows x 2 columns]

In [ ]:
#поиск издательств с названием из двух и более слов
request_11 = """
SELECT book.title,
       publisher.name
FROM book
INNER JOIN publisher
ON book.publisher_id = publisher.id
WHERE publisher.name LIKE "% %"; -- эти предложения использовать можно
"""

In [ ]:
pd.read_sql(request_11, con)

                                                 title             name
0                       Выбор вариантов: основы теории            Наука
1                                 Экономический анализ     Новое знание
2              Имитационное моделирование. Классика CS              BHV
3                              Математическая экономия              ИИЛ
4    Управление производством при нечеткой исходной...  Энергоатомиздат
..                                                 ...              ...
821        Теория графов: алгоритмы обработки деревьев            Наука
822                  Микроэкономика. Принципы и анализ              АНХ
823  Проектирование интегрированных систем библиоте...            ГПНТБ
824                    Экономико-математические методы             КГТУ
825             Когомологий бесконечномерных алгебр Ли            Наука

[826 rows x 2 columns]

In [ ]:
request_11 = """
SELECT book.title,
       publisher.name
FROM book
INNER JOIN publisher
ON book.publisher_id = publisher.id
WHERE publisher.name LIKE "% %"; -- эти предложения использовать можно
"""


# SELECT columns
#  FROM table1
#  LEFT [OUTER] JOIN table2
#    ON table1.column = table2.column;

## Домашнее задание

В рамках задания вам необходимо сделать выборку данных с помощью запросов SQL.

Получите результирующее множество из БД в соответствии с заданными условиями выборки, сортировки, группировки данных:

1. Выведите авторов, имеющихся в базе.
2. Найдите всех авторов с инициалами "С. А.". Автор в базе определяется так: И. О. Фамилия
3. Выведите список книг, выпущенных в издательстве "Мир".
4. Выведите количество книг, принадлежащих каждой из категорий. Результат отсортировать по возрастанию.
5. Выведите количество книг, выпущенных в каждом издательстве. В итоговом списке оставьте только те издательства, которые выпустили 3 и более книг. Результат отсортировать по убыванию.
6. Выведите список книг, автором которых являлся <<С. А. Айвазян>>.
7. В каких издательствах и сколько выпускались книги за авторством <<С. А. Айвазян>>. Результат отсортировать по убыванию.

**Структура БД**

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=160L6VoP2kz8mJfpFuLWF6_SdoVcvkT-J' width="400" height="400" />
<figcaption>Структура базы </figcaption></center>
</figure>

# Избранные вопросы

## Подключение и работа с удаленной БД

Работа с СУБД MySQL

1. Устанавливаем библиотеку
``` python
!pip install mysql-connector-python
```
2. Подключаем библиотеку к проекту -> создаем соединение с удаленной БД -> работаем с БД -> закрываем соединение.

```python

import mysql.connector

#устанавливаем параметры подключения
config = {
    'host' : 'your_host',
    'user' : 'your_login',
    'password' : 'your_password',
    'database' : 'name_db'
    }

#создаем соединение и курсор для работы с БД
con = mysql.connector.connect(**config)
cur = con.cursor()

#пишем запросы
request = """
-- ЗДЕСЬ ЗАПРОС
"""

#выполняем запрос
cur.execute(request)

#просмотр результата
print(cur.fetchone())

#закрываем соединение
cur.close()
con.close()
```

In [ ]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.10/dist-packages (8.1.0)
Requirement already satisfied: protobuf<=4.21.12,>=4.21.1 in /usr/local/lib/python3.10/dist-packages (from mysql-connector-python) (4.21.12)

In [ ]:
import mysql.connector

#в этом файле в переменной config хранятся данные для подключения
from config_sprinthost import config

In [ ]:
#задаются параметры подлючения и создается само подключение
con = mysql.connector.connect(**config)
cur = con.cursor(buffered=True)
#https://stackoverflow.com/questions/29772337/python-mysql-connector-unread-result-found-when-using-fetchone

DatabaseError: ignored

In [ ]:
#просмотр таблиц базы
request_show_name_tables = """
SHOW TABLES
"""

cur.execute(request_show_name_tables)
print(cur.fetchall())

[('bank_dataset',)]

In [ ]:
pd.read_sql(request_show_name_tables, con)

  Tables_in_f0822407_mysql
0             bank_dataset

In [ ]:
#просмотр столбцов таблицы
#описание вывода можно посмотреть здесь https://dev.mysql.com/doc/refman/8.0/en/show-columns.html

request_show_columns_table = """
SHOW COLUMNS
FROM bank_dataset;
"""
cur.execute(request_show_columns_table)
print(cur.fetchall())

[('userid', 'int(8)', 'YES', '', None, ''), ('score', 'int(3)', 'YES', '', None, ''), ('City', 'varchar(14)', 'YES', '', None, ''), ('Gender', 'varchar(1)', 'YES', '', None, ''), ('Age', 'int(2)', 'YES', '', None, ''), ('Objects', 'int(2)', 'YES', '', None, ''), ('Balance', 'varchar(8)', 'YES', '', None, ''), ('Products', 'int(1)', 'YES', '', None, ''), ('CreditCard', 'int(1)', 'YES', '', None, ''), ('Loyalty', 'int(1)', 'YES', '', None, ''), ('estimated_salary', 'decimal(8,2)', 'YES', '', None, ''), ('Churn', 'int(1)', 'YES', '', None, '')]

In [ ]:
pd.read_sql(request_show_columns_table, con)

               Field          Type Null Key Default Extra
0             userid        int(8)  YES        None
1              score        int(3)  YES        None
2               City   varchar(14)  YES        None
3             Gender    varchar(1)  YES        None
4                Age        int(2)  YES        None
5            Objects        int(2)  YES        None
6            Balance    varchar(8)  YES        None
7           Products        int(1)  YES        None
8         CreditCard        int(1)  YES        None
9            Loyalty        int(1)  YES        None
10  estimated_salary  decimal(8,2)  YES        None
11             Churn        int(1)  YES        None

In [ ]:
show_when_8 = """
SELECT AVG(estimated_salary) AS 'Средний доход',
       AVG(Age) AS 'Средний возраст',
       City AS 'Город'
FROM bank_dataset
WHERE City IN ('Ярославль', 'Рыбинск') AND
      (Age BETWEEN 18 AND 65) AND
      (Balance IS NOT NULL)
GROUP BY City
"""
pd.read_sql(show_when_8, con)

   Средний доход  Средний возраст      Город
0   99278.763510          38.0083    Рыбинск
1   99963.653774          37.6134  Ярославль

In [ ]:
#Задание: из двух таблиц `users` `messages` собрать сведения по клиентам их сообщениям

request_13 = """
SELECT *
FROM users
INNER JOIN messages
ON users.user_id = messages.user_id
"""
pd.read_sql(request_13, con)

,user_id,age,churn_date,city,first_name,last_name,reg_date,tariff,id,message_date,user_id
0,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra,1000_0,2018-06-27,1000
1,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra,1000_1,2018-10-08,1000
2,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra,1000_10,2018-05-30,1000
3,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra,1000_100,2018-08-20,1000
4,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra,1000_101,2018-07-22,1000
...,...,...,...,...,...,...,...,...,...,...,...
123031,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart,1499_95,2018-11-15,1499
123032,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart,1499_96,2018-12-23,1499
123033,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart,1499_97,2018-10-01,1499
123034,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart,1499_98,2018-12-25,1499
123035,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart,1499_99,2018-12-24,1499

In [ ]:
#выполнение и просмотр результата
cur.execute(q)
cur.fetchmany(5)

[(1000, 52, '', 'Краснодар', 'Рафаил', 'Верещагин', '2018-05-25', 'ultra'),
 (1001, 41, '', 'Москва', 'Иван', 'Ежов', '2018-11-01', 'smart'),
 (1002, 59, '', 'Стерлитамак', 'Евгений', 'Абрамович', '2018-06-17', 'smart'),
 (1003, 23, '', 'Москва', 'Белла', 'Белякова', '2018-08-17', 'ultra'),
 (1004, 68, '', 'Новокузнецк', 'Татьяна', 'Авдеенко', '2018-05-14', 'ultra')]

In [ ]:
q1 = """
SELECT COUNT(*)
FROM users
WHERE city = 'Краснодар'
"""

In [ ]:
cur.execute(q1)
print(cur.fetchone())

(11,)

In [ ]:
#закрытие подключения
# cur.close()
# con.close()

## Функции `CASE` и `IF`

Функция `CASE` проверяет истинность набора условий и в зависимости от результата проверки может возвращать тот или иной результат. Это выражение имеет следующую форму:

```sql
CASE
    WHEN условие_1 THEN результат_1
    WHEN условие_2 THEN результат_2
    .................................
    WHEN условие_N THEN результат_N
    [ELSE альтернативный_результат]
END
```

Функция `|IF` в зависимости от результата условного выражения возвращает одно из двух значений. Общая форма функции выглядит следующим образом:

```sql
IF(условие, значение_1, значение_2)
```
Если условие, передаваемое в качестве первого параметра, верно, то возвращается первое значение, иначе возвращается второе значение.

Функция `IF` может быть вложенной.

In [ ]:
# если доход меньше 50000, то налог, начисляется по ставке 13%, если больше 500000, то по ставке 15%

request_14 = """
SELECT estimated_salary,
       CASE
       WHEN estimated_salary >= 50000 THEN 0.15*estimated_salary
       ELSE 0.13*estimated_salary
       END as nalog
FROM bank_dataset
"""
pd.read_sql(request_14,con)

      estimated_salary       nalog
0            101348.88  15202.3320
1            112542.58  16881.3870
2            113931.57  17089.7355
3             93826.63  14073.9945
4             79084.10  11862.6150
...                ...         ...
9995          96270.64  14440.5960
9996         101699.77  15254.9655
9997          42085.58   5471.1254
9998          92888.52  13933.2780
9999          38190.78   4964.8014

[10000 rows x 2 columns]

In [ ]:
request_15 = """
SELECT estimated_salary, City, Gender,
       IF((City = 'Рыбинск') AND (Gender = 'Ж'), IF(age > 34, 1, -1), 2) as fm_from_rybinsk
FROM bank_dataset
"""
pd.read_sql(request_15, con)

      estimated_salary            City Gender  fm_from_rybinsk
0            101348.88       Ярославль      Ж                2
1            112542.58         Рыбинск      Ж                1
2            113931.57       Ярославль      Ж                2
3             93826.63       Ярославль      Ж                2
4             79084.10         Рыбинск      Ж                1
...                ...             ...    ...              ...
9995          96270.64       Ярославль      М                2
9996         101699.77       Ярославль      М                2
9997          42085.58       Ярославль      Ж                2
9998          92888.52  Ростов Великий      М                2
9999          38190.78       Ярославль      Ж                2

[10000 rows x 4 columns]

In [ ]:
request_16 = """
SELECT estimated_salary,
       CASE
       WHEN estimated_salary >= 50000 THEN 0.15*estimated_salary
       ELSE 0.13*estimated_salary
       END as nalog
FROM bank_dataset
"""
pd.read_sql(request_15,con)

In [ ]:
#Задание: из двух таблиц `users`, `messages` и `calls` собрать сведения по клиентам их сообщениям и звонкам

request_16 = """
SELECT *
FROM messages
INNER JOIN users
ON users.user_id = messages.user_id
"""
pd.read_sql(request_16, con)

,id,message_date,user_id,user_id,age,churn_date,city,first_name,last_name,reg_date,tariff
0,1000_0,2018-06-27,1000,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra
1,1000_1,2018-10-08,1000,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra
2,1000_10,2018-05-30,1000,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra
3,1000_100,2018-08-20,1000,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra
4,1000_101,2018-07-22,1000,1000,52,,Краснодар,Рафаил,Верещагин,2018-05-25,ultra
...,...,...,...,...,...,...,...,...,...,...,...
123031,1499_95,2018-11-15,1499,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart
123032,1499_96,2018-12-23,1499,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart
123033,1499_97,2018-10-01,1499,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart
123034,1499_98,2018-12-25,1499,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart
123035,1499_99,2018-12-24,1499,1499,35,,Пермь,Гектор,Корнилов,2018-09-27,smart

In [ ]:
123036

# Работа с таблицей

## **Добавление новой таблицы в базу данных**


В базу данных можно добавлять одну или несколько новых таблиц. Алгоритм создания новой таблицы следующий:
1. Определяем структуру создаваемой таблицы:
     - уникальное имя новой таблицы в пределах базы данных;
     - уникальные имена столбцов в пределах таблицы. Соответствующием им типы и ограничения;
2. Пишем запрос на добавление новой таблицы. Для этого используется следующая  инструкция `SQL`
```sql
CREATE TABLE [IF NOT EXISTS] table_name (
	column_1 data_type_col_1 PRIMARY KEY,
   	column_2 data_type_col_2  NOT NULL,
	column_3 data_type_col_3 DEFAULT 0
);
```
Здесь
    - `[IF NOT EXISTS]` -- необязательный параметр, проверяющий наличие в базе данных таблицы с именем `table_name`. Если такой таблицы нет, то она будет создана. В противном случае, запрос корректно завершит свою работу. Если в базе данных уже имеется таблица с именем `table_name` то выполнение запроса без указания опции `[IF NOT EXISTS]` приведет к ошибке;
    - `table_name` -- имя создаваемой таблицы;
    - `column_1`, `column_2` и `column_3` -- имена столбцов создаваемой таблицы `table_name`, а `data_type_col_1`, `data_type_col_2` и `data_type_col_3` соответствующие им типы данных `SQLite`. Для каждого столбца могут быть заданы ограничения `PRIMARY KEY`, `UNIQUE`, `NOT NULL` и `CHECK`.

В `Python` запрос следует писать в виде строки. Удобно его оформить в несколько строк.

3. Выполняем запрос с помощью метода `.execute()` объекта `Cursor`.
4. Сохраняем изменения с помощью метода `.commit()` объекта `Connection`.

In [ ]:
cur.close()
con.close()

In [ ]:
import sqlite3

In [ ]:
con = sqlite3.connect('chat_bot.db')
cur = con.cursor()

In [ ]:
# запрос на создание таблицы с некоторой структурой
request_create_one_table = """
CREATE TABLE IF NOT EXISTS student (id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    age INTEGER DEFAULT 20,
    gender TEXT DEFAULT 'Пол не указан')
"""

In [ ]:
#выполнение запроса
cur.execute(request_create_one_table)

In [ ]:
# сохранение изменений в БД
con.commit()

In [ ]:
q = """
SELECT

"""

### **Добавление нескольких новых таблиц в базу данных**

Имеется возможность добавить сразу несколько таблиц в базу данных. Для этого нужно написать несколько соответствующих запросов `CREATE TABLE` и выполнить их методом `.executescript()` объекта Cursor. Каждый запрос завершается символом `;`.

In [ ]:
request_create_some_tables = """
BEGIN;
CREATE TABLE IF NOT EXISTS groups (id INTEGER PRIMARY KEY,
    spec TEXT NOT NULL,
    year INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS disc (id INTEGER PRIMARY KEY,
    name_discipline TEXT NOT NULL,
    volume_hour INTEGER NOT NULL
    );
COMMIT
"""

In [ ]:
cur.executescript(request_create_some_tables)

Для просмотра имен таблиц в базе данных можно использовать следующий запрос
```sql
SELECT name
FROM sqlite_master
```

Здесь `sqlite_master` -- таблица, имеющаяся в каждой базе данных `SQLite`, в которой содержатся все остальные таблицы. Таблица `sqlite_master` имеет [следующую структуру](https://habr.com/ru/post/223451/)

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=15rAr5_zhErv6g21LOIwdRxI9U0_O0LJP' width="600" height="350" />
<figcaption>Структура таблицы `sqlite_master`</figcaption></center>
</figure>

Для таблиц поле `type` всегда будет `table`, а поле `name` будет именем таблицы.

Для просмотра результата запроса можно воспользоваться методом `.fetchall()`

In [ ]:
#запрос на имена таблиц
request_show_table_name = """
SELECT name
FROM sqlite_master
"""

In [ ]:
#выполнение запроса и просмотр результата
res = cur.execute(request_show_table_name)
res.fetchall()

# for name in res.fetchall():
#     print(name[0])

[('student',), ('groups',), ('disc',)]

In [ ]:
import pandas as pd

In [ ]:
pd.read_sql(request_show_table_name, con = conn)

      name
0  student
1   groups
2     disc

## **Добавление данных в таблицу**

С учетом выполненных выше инструкций имеем следующую структуру базы данных

<figure>
<center>
<img src='https://drive.google.com/uc?export=view&id=1ic2q5jRloH8or2PpmjtR2xZBYpMsQGOA' width="300" height="300" />
<figcaption>Структура таблицы `sqlite_master`</figcaption></center>
</figure>

Рассмотрим теперь вопрос добавления новых данных -- (строки/строк) -- в имеющиеся таблицы.

Для добавления новой строки (строк) используется следующий алгоритм.
1. Написание запроса добавления данных (строки/строк) в таблицу.
```sql
INSERT INTO table_name (column1, column2,..)
VALUES (value1,	value2,...);
```
Здесь
    - `table_name` -- имя таблицы, в которую нужно внести новые данные;
    - `column1`, `column2` -- имена столбцов таблицы;
    - `value1`,	`value2` -- вносимые данные для соответствующих столбцов.
2. Выполнение запроса с помощью метода `.execute()`.
3. Сохранение изменений с помощью метода `.commit()`.

In [ ]:
#запрос на добавление одной строки в таблицу student
insert_one_row_in_table = """
INSERT INTO student (first_name, last_name, age, gender)
VALUES ('Сергей', 'Иванов', 21, 'м')
"""

**Примечание:** обратите внимание, что для столбца `id`, являющегося для данной таблицы первичным ключом, значение можно не указывать.

In [ ]:
#выполнение запроса
cur.execute(insert_one_row_in_table)

In [ ]:
#сохранение изменений
conn.commit()

In [ ]:
# просмотр результата
request_show_all = """
SELECT *
FROM student
"""
cur.execute(request_show_all).fetchall()

[(1, 'Сергей', 'Иванов', 21, 'м')]

In [ ]:
pd.read_sql(request_show_all, con = conn)

   id first_name last_name  age gender
0   1     Сергей    Иванов   21      м

**Примечание:**

- Список столбцов в запросе `INSERT` является необязательным. Если он отсутствуете, то необходимо указать значения для всех столбцов таблицы -- количество добавляемых значений должно совпадать с количеством столбцов в таблице. **Однако рекомендуется включать список столбцов после имени таблицы**.

In [ ]:
#запрос на добавление одной строки в таблицу student без указания списка столбцов
insert_one_row_in_table_without_columns = """
INSERT INTO student
VALUES (2, 'Полина', 'Сидорова', 22, 'ж')
"""
# Обратите внимание,
# что в данном случае необходимо вносить значение
# для поля, являющегося первичным ключем.

In [ ]:
#выполнение запроса и сохранение изменений
cur.execute(insert_one_row_in_table_without_columns)
conn.commit()

In [ ]:
#просмотр результата
cur.execute('SELECT * from student').fetchall()

[(1, 'Сергей', 'Иванов', 21, 'м'), (2, 'Полина', 'Сидорова', 22, 'ж')]

In [ ]:
df = pd.read_sql(request_show_all, con = conn)
df[(df.gender == 'м')]

   id first_name last_name  age gender
0   1     Сергей    Иванов   21      м

In [ ]:
#запрос на добавление одной строки в таблицу student
insert_one_row_in_table = """
INSERT INTO student (last_name, first_name)
VALUES ('Иванов', 'Сергей')
"""

In [ ]:
cur.execute(insert_one_row_in_table)
conn.commit()

In [ ]:
cur.execute('SELECT * from student').fetchall()

[(1, 'Сергей', 'Иванов', 21, 'м'),
 (2, 'Полина', 'Сидорова', 22, 'ж'),
 (3, 'Сергей', 'Иванов', 20, 'Пол не указан')]

In [ ]:
pd.read_sql(request_show_all, con = conn)

   id first_name last_name  age         gender
0   1     Сергей    Иванов   21              м
1   2     Полина  Сидорова   22              ж
2   3     Сергей    Иванов   20  Пол не указан

Добавление нескольких строк можно реализовать
- путем их явного задания после оператора `VALUES`;
- путем их неявного задания в виде списка и использования метода `executemany()`.

In [ ]:
#запрос на добавление нескольких строк в таблицу student
insert_some_rows_in_table = """
INSERT INTO student (first_name, last_name, gender, age)
VALUES ('Алексей', 'Гуськов', 'м', 23),
       ('Екатерина', 'Риманова', 'ж', 22)
"""

**Примечание:** Обратите внимание, что порядок следования добавляемых значений должен соответствовать порядку перечисления столбцов. Иными словами, порядок перечисления столбцов не принципиален, однако, добавляемые значения должны соответствовать указанному перечислению столбцов.

In [ ]:
cur.execute(insert_some_rows_in_table)
conn.commit()

In [ ]:
cur.execute('SELECT * from student').fetchall()

[(1, 'Сергей', 'Иванов', 21, 'м'),
 (2, 'Полина', 'Сидорова', 22, 'ж'),
 (3, 'Сергей', 'Иванов', 20, 'Пол не указан'),
 (4, 'Алексей', 'Гуськов', 23, 'м'),
 (5, 'Екатерина', 'Риманова', 22, 'ж')]

In [ ]:
insert_rows = [
    ('Андрей', 'Пеньков', 24, 'м'),
    ('Ирина', 'Кочергина', 23, 'ж')
]



cur.executemany("""INSERT INTO student (first_name, last_name, age, gender)
VALUES(?, ?, ?, ? )""", insert_rows)
conn.commit()

In [ ]:
cur.execute('SELECT * from student').fetchall()

[(1, 'Сергей', 'Иванов', 21, 'м'),
 (2, 'Полина', 'Сидорова', 22, 'ж'),
 (3, 'Сергей', 'Иванов', 20, 'Пол не указан'),
 (4, 'Алексей', 'Гуськов', 23, 'м'),
 (5, 'Екатерина', 'Риманова', 22, 'ж'),
 (6, 'Андрей', 'Пеньков', 24, 'м'),
 (7, 'Ирина', 'Кочергина', 23, 'ж')]

## Редактирование данных в таблице

Для редактирования (изменения значений) существующих записей в таблице необходимо использовать оператор `UPDATE`. Оператор имеет следующий синтаксис:
```sql
UPDATE table_name
SET column_1 = new_value_1,
    column_2 = new_value_2
WHERE
    search_condition
ORDER column_or_expression
LIMIT row_count OFFSET offset_value;
```
Здесь
- `table_name` -- имя таблицы, в которой необходимо изменить данные;
- `column_1`, `column_2` и `new_value_1`, `new_value_2` -- названия столбцов, для которых нужно установить новые значения;
- `search_condition` -- условия или выражения, которые должны быть выполнены для обновления записей;
- row_count -- количество строк для обновления.

In [ ]:
#Данный запрос изменит в таблице `student`
#значения двух полей `last_name` и `first_name`
#у всех записей таблицы на `Иван` и `Иванов`, соответственно.

# request_update_some_columns = """
# UPDATE student
# SET last_name  = 'Иванов',
#     first_name  = 'Иван'
# """

# cur.execute(request_update_some_columns)
# conn.commit()

# pd.read_sql(request_update_some_columns, con = conn)

In [ ]:
pd.read_sql(request_show_all, con = conn)

   id first_name  last_name  age         gender
0   1     Сергей     Иванов   21              м
1   2     Полина   Сидорова   22              ж
2   3     Сергей     Иванов   20  Пол не указан
3   4    Алексей    Гуськов   23              м
4   5  Екатерина   Риманова   22              ж
5   6     Андрей    Пеньков   24              м
6   7      Ирина  Кочергина   23              ж

In [ ]:
#запрос на изменение `last_name` и `first_name` у одной записи

request_update_one_record = """
UPDATE student
SET last_name  = 'Федоров',
    first_name  = 'Федор'
LIMIT 3;
"""

cur.execute(request_update_one_record)
conn.commit()

pd.read_sql(request_show_all, con = conn)

   id first_name  last_name  age         gender
0   1      Федор    Федоров   21              м
1   2      Федор    Федоров   22              ж
2   3      Федор    Федоров   20  Пол не указан
3   4    Алексей    Гуськов   23              м
4   5  Екатерина   Риманова   22              ж
5   6     Андрей    Пеньков   24              м
6   7      Ирина  Кочергина   23              ж